2023-12-26 12:58:26,422 CRITICAL server_logs_config.py Test critical event
2023-12-26 12:58:26,422 ERROR server_logs_config.py Test error ivent
2023-12-26 12:58:26,422 DEBUG server_logs_config.py Test debug ivent
2023-12-26 12:58:26,422 INFO server_logs_config.py Test info ivent
2023-12-26 13:14:45,381 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 13:14:45,382 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 13:14:45,382 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 13:14:45,383 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/server.py']
2023-12-26 13:14:45,383 DEBUG server.py Аргументы успешно загружены.
2023-12-26 13:14:45,390 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 14:09:13,286 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:09:13,286 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:09:13,286 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 14:09:13,286 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/server.py']
2023-12-26 14:09:13,286 DEBUG server.py Аргументы успешно загружены.
2023-12-26 14:09:13,288 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 14:09:51,747 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:09:51,747 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:09:51,747 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 14:09:51,747 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/server.py']
2023-12-26 14:09:51,748 DEBUG server.py Аргументы успешно загружены.
2023-12-26 14:09:51,748 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 14:29:01,723 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:29:01,723 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:29:01,723 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 14:29:01,723 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/server.py']
2023-12-26 14:29:01,724 DEBUG server.py Аргументы успешно загружены.
2023-12-26 14:29:01,729 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 14:30:41,768 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:30:41,768 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:30:41,769 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 14:30:41,769 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/server.py']
2023-12-26 14:30:41,769 DEBUG server.py Аргументы успешно загружены.
2023-12-26 14:30:41,774 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 14:43:52,353 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:43:52,353 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:43:52,354 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 14:43:52,354 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/server.py']
2023-12-26 14:43:52,354 DEBUG server.py Аргументы успешно загружены.
2023-12-26 14:43:52,356 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 14:45:17,962 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:45:17,962 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:45:17,963 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 14:45:17,963 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/server.py']
2023-12-26 14:45:17,963 DEBUG server.py Аргументы успешно загружены.
2023-12-26 14:45:17,965 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 14:45:51,362 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:45:51,362 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:45:51,363 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 14:45:51,363 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/server.py']
2023-12-26 14:45:51,363 DEBUG server.py Аргументы успешно загружены.
2023-12-26 14:45:51,365 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 14:51:14,528 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:51:14,528 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 14:51:14,528 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 14:51:14,528 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/server.py']
2023-12-26 14:51:14,529 DEBUG server.py Аргументы успешно загружены.
2023-12-26 14:51:14,534 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 15:24:44,517 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 15:24:44,517 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 15:24:44,518 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 15:24:44,518 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 15:24:44,519 DEBUG server.py Аргументы успешно загружены.
2023-12-26 15:24:44,520 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 15:31:32,794 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 15:31:32,795 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 15:31:32,795 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 15:31:32,795 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 15:31:32,796 DEBUG server.py Аргументы успешно загружены.
2023-12-26 15:31:32,799 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 16:39:25,437 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 16:39:25,438 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 16:39:25,438 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 16:39:25,438 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 16:39:25,439 DEBUG server.py Аргументы успешно загружены.
2023-12-26 16:39:25,439 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 16:40:09,004 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52459)
2023-12-26 16:40:09,506 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52459)>,) , {}. Вызов из модуля core.utils
2023-12-26 16:42:19,935 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 16:42:19,935 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 16:42:19,935 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 16:42:19,935 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 16:42:19,936 DEBUG server.py Аргументы успешно загружены.
2023-12-26 16:42:19,937 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 16:42:51,416 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52598)
2023-12-26 16:42:51,919 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52598)>,) , {}. Вызов из модуля core.utils
2023-12-26 16:42:51,919 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703598171.422806, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxM9I6SII7JzDl+/zfY8D\nN6A/UwLmB1c670wvwYLEnrO/UXFG5FaqQ3Ou9UvKq8rczHVdtIRN2uh7bAncodoc\nT2AhumCpPA0xjSg7X6f4f60wSbrCF0Dl/0vjE7ByCYYvQ/2ZKaZfQ0kmx4Qios6Q\nT77gTqWvUe187wR5LRf3uYUU2jjQPkww9Bhi4qjwGVQv2DDqpqGHo+MLNSYJVzvR\nDCX7/PJ/iW14xtt5tZwgowdZkyZUqma6/RigEH+6HWaSDKQ7yBm1U9APWcHcyMur\nsh7denm0wuWWQGG0AqDxxYTFB7TOfjMdagdRS3unKEgTPGe4gh3650/ATknc+L3b\n7wIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 16:42:51,919 DEBUG core.py Start auth process for {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxM9I6SII7JzDl+/zfY8D\nN6A/UwLmB1c670wvwYLEnrO/UXFG5FaqQ3Ou9UvKq8rczHVdtIRN2uh7bAncodoc\nT2AhumCpPA0xjSg7X6f4f60wSbrCF0Dl/0vjE7ByCYYvQ/2ZKaZfQ0kmx4Qios6Q\nT77gTqWvUe187wR5LRf3uYUU2jjQPkww9Bhi4qjwGVQv2DDqpqGHo+MLNSYJVzvR\nDCX7/PJ/iW14xtt5tZwgowdZkyZUqma6/RigEH+6HWaSDKQ7yBm1U9APWcHcyMur\nsh7denm0wuWWQGG0AqDxxYTFB7TOfjMdagdRS3unKEgTPGe4gh3650/ATknc+L3b\n7wIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 16:46:21,983 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 16:46:21,983 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 16:46:21,983 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 16:46:21,983 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 16:46:21,983 DEBUG server.py Аргументы успешно загружены.
2023-12-26 16:46:21,984 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 16:46:57,125 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 16:46:57,126 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 16:46:57,126 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 16:46:57,126 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 16:46:57,126 DEBUG server.py Аргументы успешно загружены.
2023-12-26 16:46:57,127 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 16:48:20,605 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 16:48:20,605 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 16:48:20,605 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 16:48:20,605 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 16:48:20,606 DEBUG server.py Аргументы успешно загружены.
2023-12-26 16:48:20,607 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 16:50:20,250 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52797)
2023-12-26 16:50:20,752 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52797)>,) , {}. Вызов из модуля core.utils
2023-12-26 16:50:20,752 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703598620.256979, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxM9I6SII7JzDl+/zfY8D\nN6A/UwLmB1c670wvwYLEnrO/UXFG5FaqQ3Ou9UvKq8rczHVdtIRN2uh7bAncodoc\nT2AhumCpPA0xjSg7X6f4f60wSbrCF0Dl/0vjE7ByCYYvQ/2ZKaZfQ0kmx4Qios6Q\nT77gTqWvUe187wR5LRf3uYUU2jjQPkww9Bhi4qjwGVQv2DDqpqGHo+MLNSYJVzvR\nDCX7/PJ/iW14xtt5tZwgowdZkyZUqma6/RigEH+6HWaSDKQ7yBm1U9APWcHcyMur\nsh7denm0wuWWQGG0AqDxxYTFB7TOfjMdagdRS3unKEgTPGe4gh3650/ATknc+L3b\n7wIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 16:50:20,753 DEBUG core.py Start auth process for {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxM9I6SII7JzDl+/zfY8D\nN6A/UwLmB1c670wvwYLEnrO/UXFG5FaqQ3Ou9UvKq8rczHVdtIRN2uh7bAncodoc\nT2AhumCpPA0xjSg7X6f4f60wSbrCF0Dl/0vjE7ByCYYvQ/2ZKaZfQ0kmx4Qios6Q\nT77gTqWvUe187wR5LRf3uYUU2jjQPkww9Bhi4qjwGVQv2DDqpqGHo+MLNSYJVzvR\nDCX7/PJ/iW14xtt5tZwgowdZkyZUqma6/RigEH+6HWaSDKQ7yBm1U9APWcHcyMur\nsh7denm0wuWWQGG0AqDxxYTFB7TOfjMdagdRS3unKEgTPGe4gh3650/ATknc+L3b\n7wIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 16:50:20,760 DEBUG core.py Correct username, starting passwd check.
2023-12-26 17:22:22,955 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 17:22:22,955 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 17:22:22,956 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 17:22:22,956 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 17:22:22,957 DEBUG server.py Аргументы успешно загружены.
2023-12-26 17:22:22,958 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 17:22:40,824 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 17:22:40,824 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 17:22:40,825 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 17:22:40,825 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 17:22:40,825 DEBUG server.py Аргументы успешно загружены.
2023-12-26 17:22:40,827 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 17:23:04,462 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 17:23:04,462 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 17:23:04,462 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 17:23:04,462 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 17:23:04,463 DEBUG server.py Аргументы успешно загружены.
2023-12-26 17:23:04,464 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 17:23:21,465 INFO core.py Установлено соедение с ПК ('127.0.0.1', 53661)
2023-12-26 17:23:21,966 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53661)>,) , {}. Вызов из модуля core.utils
2023-12-26 17:23:21,967 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703600601.473995, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxM9I6SII7JzDl+/zfY8D\nN6A/UwLmB1c670wvwYLEnrO/UXFG5FaqQ3Ou9UvKq8rczHVdtIRN2uh7bAncodoc\nT2AhumCpPA0xjSg7X6f4f60wSbrCF0Dl/0vjE7ByCYYvQ/2ZKaZfQ0kmx4Qios6Q\nT77gTqWvUe187wR5LRf3uYUU2jjQPkww9Bhi4qjwGVQv2DDqpqGHo+MLNSYJVzvR\nDCX7/PJ/iW14xtt5tZwgowdZkyZUqma6/RigEH+6HWaSDKQ7yBm1U9APWcHcyMur\nsh7denm0wuWWQGG0AqDxxYTFB7TOfjMdagdRS3unKEgTPGe4gh3650/ATknc+L3b\n7wIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 17:23:21,967 DEBUG core.py Start auth process for {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxM9I6SII7JzDl+/zfY8D\nN6A/UwLmB1c670wvwYLEnrO/UXFG5FaqQ3Ou9UvKq8rczHVdtIRN2uh7bAncodoc\nT2AhumCpPA0xjSg7X6f4f60wSbrCF0Dl/0vjE7ByCYYvQ/2ZKaZfQ0kmx4Qios6Q\nT77gTqWvUe187wR5LRf3uYUU2jjQPkww9Bhi4qjwGVQv2DDqpqGHo+MLNSYJVzvR\nDCX7/PJ/iW14xtt5tZwgowdZkyZUqma6/RigEH+6HWaSDKQ7yBm1U9APWcHcyMur\nsh7denm0wuWWQGG0AqDxxYTFB7TOfjMdagdRS3unKEgTPGe4gh3650/ATknc+L3b\n7wIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 17:23:21,974 DEBUG core.py Correct username, starting passwd check.
2023-12-26 17:24:30,093 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 17:24:30,093 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 17:24:30,093 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 17:24:30,093 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 17:24:30,094 DEBUG server.py Аргументы успешно загружены.
2023-12-26 17:24:30,095 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 17:24:40,732 INFO core.py Установлено соедение с ПК ('127.0.0.1', 53734)
2023-12-26 17:24:41,234 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53734)>,) , {}. Вызов из модуля core.utils
2023-12-26 17:24:41,235 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703600680.741823, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxM9I6SII7JzDl+/zfY8D\nN6A/UwLmB1c670wvwYLEnrO/UXFG5FaqQ3Ou9UvKq8rczHVdtIRN2uh7bAncodoc\nT2AhumCpPA0xjSg7X6f4f60wSbrCF0Dl/0vjE7ByCYYvQ/2ZKaZfQ0kmx4Qios6Q\nT77gTqWvUe187wR5LRf3uYUU2jjQPkww9Bhi4qjwGVQv2DDqpqGHo+MLNSYJVzvR\nDCX7/PJ/iW14xtt5tZwgowdZkyZUqma6/RigEH+6HWaSDKQ7yBm1U9APWcHcyMur\nsh7denm0wuWWQGG0AqDxxYTFB7TOfjMdagdRS3unKEgTPGe4gh3650/ATknc+L3b\n7wIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 17:24:41,235 DEBUG core.py Start auth process for {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxM9I6SII7JzDl+/zfY8D\nN6A/UwLmB1c670wvwYLEnrO/UXFG5FaqQ3Ou9UvKq8rczHVdtIRN2uh7bAncodoc\nT2AhumCpPA0xjSg7X6f4f60wSbrCF0Dl/0vjE7ByCYYvQ/2ZKaZfQ0kmx4Qios6Q\nT77gTqWvUe187wR5LRf3uYUU2jjQPkww9Bhi4qjwGVQv2DDqpqGHo+MLNSYJVzvR\nDCX7/PJ/iW14xtt5tZwgowdZkyZUqma6/RigEH+6HWaSDKQ7yBm1U9APWcHcyMur\nsh7denm0wuWWQGG0AqDxxYTFB7TOfjMdagdRS3unKEgTPGe4gh3650/ATknc+L3b\n7wIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 17:24:41,241 DEBUG core.py Correct username, starting passwd check.
2023-12-26 17:24:41,242 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/core.py", line 97, in run
    self.process_client_message(get_message(client_with_message), client_with_message)
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/decos.py", line 59, in checker
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/core.py", line 159, in process_client_message
    self.autorize_user(message, client)
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/core.py", line 321, in autorize_user
    hash = hashlib.pbkdf2_hmac(password_hash, random_str, "MD5")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: pbkdf2_hmac() missing required argument 'iterations' (pos 4)
2023-12-26 17:24:41,243 INFO core.py Клиент ('127.0.0.1', 53734) отключился от сервера.
2023-12-26 17:24:59,225 INFO core.py Установлено соедение с ПК ('127.0.0.1', 53753)
2023-12-26 17:24:59,727 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53753)>,) , {}. Вызов из модуля core.utils
2023-12-26 17:24:59,728 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703600699.2348511, 'user': {'account_name': 'asdf', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz3XTGF3qreijSLfFRuoh\nNUjw9gWbaJ12rK6prhhaQWfNNMbEzHv1rYSFMjprtYyd7v3kmgfLBtpdbJ2arzg2\nh8yAIkfJ2SuaD1Qjm4BEJCpWB2ZsZIbXzFl73eV7qXQFDud/XVX4YlHH//mJqiQu\ncaLH6DQYOUSxMtQXtKz/poqRi/QckH0k6JFABXe9Sp44EXinbo6FAadsAbrdp/Dh\ndZZMVXKqbhHnUo+5YbwsWn7XPOgGZ578VYfxMt6KgFf48VuUdE77I2yKRymj1QLf\nt2N0+RTZIky2ojis9XZCWTpodgGnUge6Js9ga8/t/cS9u4SXUovDQKnphKa5F7I9\nkQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 17:24:59,728 DEBUG core.py Start auth process for {'account_name': 'asdf', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz3XTGF3qreijSLfFRuoh\nNUjw9gWbaJ12rK6prhhaQWfNNMbEzHv1rYSFMjprtYyd7v3kmgfLBtpdbJ2arzg2\nh8yAIkfJ2SuaD1Qjm4BEJCpWB2ZsZIbXzFl73eV7qXQFDud/XVX4YlHH//mJqiQu\ncaLH6DQYOUSxMtQXtKz/poqRi/QckH0k6JFABXe9Sp44EXinbo6FAadsAbrdp/Dh\ndZZMVXKqbhHnUo+5YbwsWn7XPOgGZ578VYfxMt6KgFf48VuUdE77I2yKRymj1QLf\nt2N0+RTZIky2ojis9XZCWTpodgGnUge6Js9ga8/t/cS9u4SXUovDQKnphKa5F7I9\nkQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 17:24:59,730 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2023-12-26 17:24:59,730 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53753)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}) , {}. Вызов из модуля core.utils
2023-12-26 17:25:08,319 INFO core.py Установлено соедение с ПК ('127.0.0.1', 53759)
2023-12-26 17:25:08,821 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53759)>,) , {}. Вызов из модуля core.utils
2023-12-26 17:25:08,822 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703600708.328963, 'user': {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fuQ7TRZuul+0RJvA5VW\nZLteNIkvlusnGgSn1rgAwS4jiS2uSvJ3gv07YrrCGxDtD3hPwMyTyzv+oiNGyfIG\nvtZfum4QPtDGkn3kiNZXF/Xf7BR2TcazpXLF53sOxxt/cV7gvHHNCAlRfU4LHWP5\nmY7KILz267QbcywHIlb1AxBhq4dyymfpovO/iz3FljXhJdImM+xmZBQVVjquSZLU\n4pf3dwBjyU6wSopXmN4UAGbjjbBFhPlrKuam/Ovzesx7Ai3+AO9+eIbE/tVKi06U\n7TvUIQ53ERBhgr7sgXOrlHoTs5It77jybwB7E8td3aJaJiy+vYmuUtxe15lsrRoi\nrQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 17:25:08,822 DEBUG core.py Start auth process for {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fuQ7TRZuul+0RJvA5VW\nZLteNIkvlusnGgSn1rgAwS4jiS2uSvJ3gv07YrrCGxDtD3hPwMyTyzv+oiNGyfIG\nvtZfum4QPtDGkn3kiNZXF/Xf7BR2TcazpXLF53sOxxt/cV7gvHHNCAlRfU4LHWP5\nmY7KILz267QbcywHIlb1AxBhq4dyymfpovO/iz3FljXhJdImM+xmZBQVVjquSZLU\n4pf3dwBjyU6wSopXmN4UAGbjjbBFhPlrKuam/Ovzesx7Ai3+AO9+eIbE/tVKi06U\n7TvUIQ53ERBhgr7sgXOrlHoTs5It77jybwB7E8td3aJaJiy+vYmuUtxe15lsrRoi\nrQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 17:25:08,825 DEBUG core.py Correct username, starting passwd check.
2023-12-26 17:25:08,825 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/core.py", line 97, in run
    self.process_client_message(get_message(client_with_message), client_with_message)
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/decos.py", line 59, in checker
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/core.py", line 159, in process_client_message
    self.autorize_user(message, client)
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/core.py", line 321, in autorize_user
    hash = hashlib.pbkdf2_hmac(password_hash, random_str, "MD5")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: pbkdf2_hmac() missing required argument 'iterations' (pos 4)
2023-12-26 17:25:08,827 INFO core.py Клиент ('127.0.0.1', 53759) отключился от сервера.
2023-12-26 19:58:17,161 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 19:58:17,161 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 19:58:17,161 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 19:58:17,161 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 19:58:17,162 DEBUG server.py Аргументы успешно загружены.
2023-12-26 19:58:17,163 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 19:58:29,197 INFO core.py Установлено соедение с ПК ('127.0.0.1', 55576)
2023-12-26 19:58:29,699 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55576)>,) , {}. Вызов из модуля core.utils
2023-12-26 19:58:29,700 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703609909.20669, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxM9I6SII7JzDl+/zfY8D\nN6A/UwLmB1c670wvwYLEnrO/UXFG5FaqQ3Ou9UvKq8rczHVdtIRN2uh7bAncodoc\nT2AhumCpPA0xjSg7X6f4f60wSbrCF0Dl/0vjE7ByCYYvQ/2ZKaZfQ0kmx4Qios6Q\nT77gTqWvUe187wR5LRf3uYUU2jjQPkww9Bhi4qjwGVQv2DDqpqGHo+MLNSYJVzvR\nDCX7/PJ/iW14xtt5tZwgowdZkyZUqma6/RigEH+6HWaSDKQ7yBm1U9APWcHcyMur\nsh7denm0wuWWQGG0AqDxxYTFB7TOfjMdagdRS3unKEgTPGe4gh3650/ATknc+L3b\n7wIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 19:58:29,700 DEBUG core.py Start auth process for {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxM9I6SII7JzDl+/zfY8D\nN6A/UwLmB1c670wvwYLEnrO/UXFG5FaqQ3Ou9UvKq8rczHVdtIRN2uh7bAncodoc\nT2AhumCpPA0xjSg7X6f4f60wSbrCF0Dl/0vjE7ByCYYvQ/2ZKaZfQ0kmx4Qios6Q\nT77gTqWvUe187wR5LRf3uYUU2jjQPkww9Bhi4qjwGVQv2DDqpqGHo+MLNSYJVzvR\nDCX7/PJ/iW14xtt5tZwgowdZkyZUqma6/RigEH+6HWaSDKQ7yBm1U9APWcHcyMur\nsh7denm0wuWWQGG0AqDxxYTFB7TOfjMdagdRS3unKEgTPGe4gh3650/ATknc+L3b\n7wIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 19:58:29,705 DEBUG core.py Correct username, starting passwd check.
2023-12-26 19:58:29,706 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/core.py", line 97, in run
    self.process_client_message(get_message(client_with_message), client_with_message)
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/decos.py", line 59, in checker
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/core.py", line 159, in process_client_message
    self.autorize_user(message, client)
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/core.py", line 322, in autorize_user
    hash = hmac.new(self.db.get_hash(username), random_str, "MD5")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/.pyenv/versions/3.11.2/lib/python3.11/hmac.py", line 184, in new
    return HMAC(key, msg, digestmod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/.pyenv/versions/3.11.2/lib/python3.11/hmac.py", line 53, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
2023-12-26 19:58:29,710 INFO core.py Клиент ('127.0.0.1', 55576) отключился от сервера.
2023-12-26 20:42:16,261 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:42:16,261 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:42:16,261 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 20:42:16,261 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 20:42:16,262 DEBUG server.py Аргументы успешно загружены.
2023-12-26 20:42:16,263 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 20:42:30,967 INFO core.py Установлено соедение с ПК ('127.0.0.1', 56655)
2023-12-26 20:42:31,469 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56655)>,) , {}. Вызов из модуля core.utils
2023-12-26 20:42:31,470 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703612550.973535, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxM9I6SII7JzDl+/zfY8D\nN6A/UwLmB1c670wvwYLEnrO/UXFG5FaqQ3Ou9UvKq8rczHVdtIRN2uh7bAncodoc\nT2AhumCpPA0xjSg7X6f4f60wSbrCF0Dl/0vjE7ByCYYvQ/2ZKaZfQ0kmx4Qios6Q\nT77gTqWvUe187wR5LRf3uYUU2jjQPkww9Bhi4qjwGVQv2DDqpqGHo+MLNSYJVzvR\nDCX7/PJ/iW14xtt5tZwgowdZkyZUqma6/RigEH+6HWaSDKQ7yBm1U9APWcHcyMur\nsh7denm0wuWWQGG0AqDxxYTFB7TOfjMdagdRS3unKEgTPGe4gh3650/ATknc+L3b\n7wIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 20:42:31,470 DEBUG core.py Start auth process for {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxM9I6SII7JzDl+/zfY8D\nN6A/UwLmB1c670wvwYLEnrO/UXFG5FaqQ3Ou9UvKq8rczHVdtIRN2uh7bAncodoc\nT2AhumCpPA0xjSg7X6f4f60wSbrCF0Dl/0vjE7ByCYYvQ/2ZKaZfQ0kmx4Qios6Q\nT77gTqWvUe187wR5LRf3uYUU2jjQPkww9Bhi4qjwGVQv2DDqpqGHo+MLNSYJVzvR\nDCX7/PJ/iW14xtt5tZwgowdZkyZUqma6/RigEH+6HWaSDKQ7yBm1U9APWcHcyMur\nsh7denm0wuWWQGG0AqDxxYTFB7TOfjMdagdRS3unKEgTPGe4gh3650/ATknc+L3b\n7wIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 20:42:31,476 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2023-12-26 20:42:31,476 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56655)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}) , {}. Вызов из модуля core.utils
2023-12-26 20:42:51,881 INFO core.py Установлено соедение с ПК ('127.0.0.1', 56661)
2023-12-26 20:42:52,383 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56661)>,) , {}. Вызов из модуля core.utils
2023-12-26 20:42:52,384 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703612571.887618, 'user': {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fuQ7TRZuul+0RJvA5VW\nZLteNIkvlusnGgSn1rgAwS4jiS2uSvJ3gv07YrrCGxDtD3hPwMyTyzv+oiNGyfIG\nvtZfum4QPtDGkn3kiNZXF/Xf7BR2TcazpXLF53sOxxt/cV7gvHHNCAlRfU4LHWP5\nmY7KILz267QbcywHIlb1AxBhq4dyymfpovO/iz3FljXhJdImM+xmZBQVVjquSZLU\n4pf3dwBjyU6wSopXmN4UAGbjjbBFhPlrKuam/Ovzesx7Ai3+AO9+eIbE/tVKi06U\n7TvUIQ53ERBhgr7sgXOrlHoTs5It77jybwB7E8td3aJaJiy+vYmuUtxe15lsrRoi\nrQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 20:42:52,384 DEBUG core.py Start auth process for {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fuQ7TRZuul+0RJvA5VW\nZLteNIkvlusnGgSn1rgAwS4jiS2uSvJ3gv07YrrCGxDtD3hPwMyTyzv+oiNGyfIG\nvtZfum4QPtDGkn3kiNZXF/Xf7BR2TcazpXLF53sOxxt/cV7gvHHNCAlRfU4LHWP5\nmY7KILz267QbcywHIlb1AxBhq4dyymfpovO/iz3FljXhJdImM+xmZBQVVjquSZLU\n4pf3dwBjyU6wSopXmN4UAGbjjbBFhPlrKuam/Ovzesx7Ai3+AO9+eIbE/tVKi06U\n7TvUIQ53ERBhgr7sgXOrlHoTs5It77jybwB7E8td3aJaJiy+vYmuUtxe15lsrRoi\nrQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 20:42:52,386 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2023-12-26 20:42:52,387 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56661)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}) , {}. Вызов из модуля core.utils
2023-12-26 20:43:51,624 INFO core.py Установлено соедение с ПК ('127.0.0.1', 56671)
2023-12-26 20:43:52,126 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56671)>,) , {}. Вызов из модуля core.utils
2023-12-26 20:43:52,126 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703612631.6300778, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvat3hlllruW7+1jDXBdN\nJzcnTXoGU/9h49w8MPrcbZ8Aat4+h38kA54YOP4aiOHHfi7E+LLyvFH9H5d+FjGm\nBeQ8K3xfsI0XcU9+YbzWQj7gd3+HzqrDxc6mtkZjMUNzqi4zmuU5cLFHCzFVUtp0\np0wrBP9WPN4e3o5Lmu1ijfMgVV3baiGQFAKNAvDw52v3ujbk0vY7iiIwS1vBRb88\nsMlxmSFGWrKYfhvPEte/9xJexgsFmNrxf6dHxGY5zSagVA9BUaqOpTCy6h+9zvZP\nFfB0UuvRRlAg7q7P8F9Xtx0h3EiLYG3nl37TeRZuyU3O0Gd2wzBB/f7M7LvVNbcI\nvQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 20:43:52,127 DEBUG core.py Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvat3hlllruW7+1jDXBdN\nJzcnTXoGU/9h49w8MPrcbZ8Aat4+h38kA54YOP4aiOHHfi7E+LLyvFH9H5d+FjGm\nBeQ8K3xfsI0XcU9+YbzWQj7gd3+HzqrDxc6mtkZjMUNzqi4zmuU5cLFHCzFVUtp0\np0wrBP9WPN4e3o5Lmu1ijfMgVV3baiGQFAKNAvDw52v3ujbk0vY7iiIwS1vBRb88\nsMlxmSFGWrKYfhvPEte/9xJexgsFmNrxf6dHxGY5zSagVA9BUaqOpTCy6h+9zvZP\nFfB0UuvRRlAg7q7P8F9Xtx0h3EiLYG3nl37TeRZuyU3O0Gd2wzBB/f7M7LvVNbcI\nvQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 20:43:52,128 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2023-12-26 20:43:52,128 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56671)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}) , {}. Вызов из модуля core.utils
2023-12-26 20:45:57,491 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:45:57,491 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:45:57,492 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 20:45:57,492 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 20:45:57,492 DEBUG server.py Аргументы успешно загружены.
2023-12-26 20:45:57,493 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 20:46:08,469 INFO core.py Установлено соедение с ПК ('127.0.0.1', 56717)
2023-12-26 20:46:08,970 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56717)>,) , {}. Вызов из модуля core.utils
2023-12-26 20:46:08,971 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703612768.475293, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvat3hlllruW7+1jDXBdN\nJzcnTXoGU/9h49w8MPrcbZ8Aat4+h38kA54YOP4aiOHHfi7E+LLyvFH9H5d+FjGm\nBeQ8K3xfsI0XcU9+YbzWQj7gd3+HzqrDxc6mtkZjMUNzqi4zmuU5cLFHCzFVUtp0\np0wrBP9WPN4e3o5Lmu1ijfMgVV3baiGQFAKNAvDw52v3ujbk0vY7iiIwS1vBRb88\nsMlxmSFGWrKYfhvPEte/9xJexgsFmNrxf6dHxGY5zSagVA9BUaqOpTCy6h+9zvZP\nFfB0UuvRRlAg7q7P8F9Xtx0h3EiLYG3nl37TeRZuyU3O0Gd2wzBB/f7M7LvVNbcI\nvQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 20:46:08,971 DEBUG core.py Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvat3hlllruW7+1jDXBdN\nJzcnTXoGU/9h49w8MPrcbZ8Aat4+h38kA54YOP4aiOHHfi7E+LLyvFH9H5d+FjGm\nBeQ8K3xfsI0XcU9+YbzWQj7gd3+HzqrDxc6mtkZjMUNzqi4zmuU5cLFHCzFVUtp0\np0wrBP9WPN4e3o5Lmu1ijfMgVV3baiGQFAKNAvDw52v3ujbk0vY7iiIwS1vBRb88\nsMlxmSFGWrKYfhvPEte/9xJexgsFmNrxf6dHxGY5zSagVA9BUaqOpTCy6h+9zvZP\nFfB0UuvRRlAg7q7P8F9Xtx0h3EiLYG3nl37TeRZuyU3O0Gd2wzBB/f7M7LvVNbcI\nvQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 20:46:08,975 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2023-12-26 20:46:08,975 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56717)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}) , {}. Вызов из модуля core.utils
2023-12-26 20:46:49,075 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:46:49,075 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:46:49,076 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 20:46:49,076 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 20:46:49,076 DEBUG server.py Аргументы успешно загружены.
2023-12-26 20:46:49,077 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 20:46:58,846 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:46:58,846 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:46:58,847 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 20:46:58,847 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 20:46:58,847 DEBUG server.py Аргументы успешно загружены.
2023-12-26 20:46:58,848 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 20:47:07,956 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:47:07,957 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:47:07,957 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 20:47:07,957 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 20:47:07,957 DEBUG server.py Аргументы успешно загружены.
2023-12-26 20:47:07,958 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 20:47:38,791 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:47:38,791 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:47:38,791 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 20:47:38,791 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 20:47:38,791 DEBUG server.py Аргументы успешно загружены.
2023-12-26 20:47:38,792 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 20:47:48,971 INFO core.py Установлено соедение с ПК ('127.0.0.1', 56741)
2023-12-26 20:47:49,473 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56741)>,) , {}. Вызов из модуля core.utils
2023-12-26 20:47:49,474 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703612868.978088, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvat3hlllruW7+1jDXBdN\nJzcnTXoGU/9h49w8MPrcbZ8Aat4+h38kA54YOP4aiOHHfi7E+LLyvFH9H5d+FjGm\nBeQ8K3xfsI0XcU9+YbzWQj7gd3+HzqrDxc6mtkZjMUNzqi4zmuU5cLFHCzFVUtp0\np0wrBP9WPN4e3o5Lmu1ijfMgVV3baiGQFAKNAvDw52v3ujbk0vY7iiIwS1vBRb88\nsMlxmSFGWrKYfhvPEte/9xJexgsFmNrxf6dHxGY5zSagVA9BUaqOpTCy6h+9zvZP\nFfB0UuvRRlAg7q7P8F9Xtx0h3EiLYG3nl37TeRZuyU3O0Gd2wzBB/f7M7LvVNbcI\nvQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 20:47:49,474 DEBUG core.py Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvat3hlllruW7+1jDXBdN\nJzcnTXoGU/9h49w8MPrcbZ8Aat4+h38kA54YOP4aiOHHfi7E+LLyvFH9H5d+FjGm\nBeQ8K3xfsI0XcU9+YbzWQj7gd3+HzqrDxc6mtkZjMUNzqi4zmuU5cLFHCzFVUtp0\np0wrBP9WPN4e3o5Lmu1ijfMgVV3baiGQFAKNAvDw52v3ujbk0vY7iiIwS1vBRb88\nsMlxmSFGWrKYfhvPEte/9xJexgsFmNrxf6dHxGY5zSagVA9BUaqOpTCy6h+9zvZP\nFfB0UuvRRlAg7q7P8F9Xtx0h3EiLYG3nl37TeRZuyU3O0Gd2wzBB/f7M7LvVNbcI\nvQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 20:47:49,482 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2023-12-26 20:47:49,482 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56741)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}) , {}. Вызов из модуля core.utils
2023-12-26 20:48:47,371 INFO core.py Установлено соедение с ПК ('127.0.0.1', 56762)
2023-12-26 20:48:47,873 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56762)>,) , {}. Вызов из модуля core.utils
2023-12-26 20:48:47,874 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703612927.377773, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvat3hlllruW7+1jDXBdN\nJzcnTXoGU/9h49w8MPrcbZ8Aat4+h38kA54YOP4aiOHHfi7E+LLyvFH9H5d+FjGm\nBeQ8K3xfsI0XcU9+YbzWQj7gd3+HzqrDxc6mtkZjMUNzqi4zmuU5cLFHCzFVUtp0\np0wrBP9WPN4e3o5Lmu1ijfMgVV3baiGQFAKNAvDw52v3ujbk0vY7iiIwS1vBRb88\nsMlxmSFGWrKYfhvPEte/9xJexgsFmNrxf6dHxGY5zSagVA9BUaqOpTCy6h+9zvZP\nFfB0UuvRRlAg7q7P8F9Xtx0h3EiLYG3nl37TeRZuyU3O0Gd2wzBB/f7M7LvVNbcI\nvQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 20:48:47,874 DEBUG core.py Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvat3hlllruW7+1jDXBdN\nJzcnTXoGU/9h49w8MPrcbZ8Aat4+h38kA54YOP4aiOHHfi7E+LLyvFH9H5d+FjGm\nBeQ8K3xfsI0XcU9+YbzWQj7gd3+HzqrDxc6mtkZjMUNzqi4zmuU5cLFHCzFVUtp0\np0wrBP9WPN4e3o5Lmu1ijfMgVV3baiGQFAKNAvDw52v3ujbk0vY7iiIwS1vBRb88\nsMlxmSFGWrKYfhvPEte/9xJexgsFmNrxf6dHxGY5zSagVA9BUaqOpTCy6h+9zvZP\nFfB0UuvRRlAg7q7P8F9Xtx0h3EiLYG3nl37TeRZuyU3O0Gd2wzBB/f7M7LvVNbcI\nvQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 20:48:47,877 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2023-12-26 20:48:47,880 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56762)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}) , {}. Вызов из модуля core.utils
2023-12-26 20:48:59,785 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:48:59,785 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:48:59,785 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 20:48:59,785 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 20:48:59,786 DEBUG server.py Аргументы успешно загружены.
2023-12-26 20:48:59,787 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 20:49:08,933 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:49:08,933 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:49:08,934 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 20:49:08,934 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 20:49:08,934 DEBUG server.py Аргументы успешно загружены.
2023-12-26 20:49:08,935 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 20:49:37,776 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:49:37,776 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:49:37,776 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 20:49:37,776 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 20:49:37,776 DEBUG server.py Аргументы успешно загружены.
2023-12-26 20:49:37,777 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 20:49:45,624 INFO core.py Установлено соедение с ПК ('127.0.0.1', 56773)
2023-12-26 20:49:46,125 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56773)>,) , {}. Вызов из модуля core.utils
2023-12-26 20:49:46,126 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703612985.630631, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvat3hlllruW7+1jDXBdN\nJzcnTXoGU/9h49w8MPrcbZ8Aat4+h38kA54YOP4aiOHHfi7E+LLyvFH9H5d+FjGm\nBeQ8K3xfsI0XcU9+YbzWQj7gd3+HzqrDxc6mtkZjMUNzqi4zmuU5cLFHCzFVUtp0\np0wrBP9WPN4e3o5Lmu1ijfMgVV3baiGQFAKNAvDw52v3ujbk0vY7iiIwS1vBRb88\nsMlxmSFGWrKYfhvPEte/9xJexgsFmNrxf6dHxGY5zSagVA9BUaqOpTCy6h+9zvZP\nFfB0UuvRRlAg7q7P8F9Xtx0h3EiLYG3nl37TeRZuyU3O0Gd2wzBB/f7M7LvVNbcI\nvQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 20:49:46,126 DEBUG core.py Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvat3hlllruW7+1jDXBdN\nJzcnTXoGU/9h49w8MPrcbZ8Aat4+h38kA54YOP4aiOHHfi7E+LLyvFH9H5d+FjGm\nBeQ8K3xfsI0XcU9+YbzWQj7gd3+HzqrDxc6mtkZjMUNzqi4zmuU5cLFHCzFVUtp0\np0wrBP9WPN4e3o5Lmu1ijfMgVV3baiGQFAKNAvDw52v3ujbk0vY7iiIwS1vBRb88\nsMlxmSFGWrKYfhvPEte/9xJexgsFmNrxf6dHxGY5zSagVA9BUaqOpTCy6h+9zvZP\nFfB0UuvRRlAg7q7P8F9Xtx0h3EiLYG3nl37TeRZuyU3O0Gd2wzBB/f7M7LvVNbcI\nvQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 20:50:58,331 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:50:58,331 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 20:50:58,332 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 20:50:58,332 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 20:50:58,332 DEBUG server.py Аргументы успешно загружены.
2023-12-26 20:50:58,335 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 21:10:56,720 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 21:10:56,721 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 21:10:56,721 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 21:10:56,722 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 21:10:56,722 DEBUG server.py Аргументы успешно загружены.
2023-12-26 21:10:56,723 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 21:11:27,494 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57219)
2023-12-26 21:11:27,996 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57219)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:11:27,996 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703614287.50008, 'user': {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 21:11:27,997 DEBUG core.py Start auth process for {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 21:11:28,001 DEBUG core.py Correct username, starting passwd check.
2023-12-26 21:11:28,002 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57219)>, {'response': 511, 'bin': 'b47e74084bdf60f486e12c836946f0b02ae5068bba594000b06898469bc6a204033f2de64fbbb0c578a9f77d8be3e605a46504f3e29a29002dccfadb19094ad0'}) , {}. Вызов из модуля core.utils
2023-12-26 21:11:28,002 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57219)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:13:26,028 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 21:13:26,028 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 21:13:26,028 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 21:13:26,028 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 21:13:26,029 DEBUG server.py Аргументы успешно загружены.
2023-12-26 21:13:26,029 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 21:13:33,336 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57253)
2023-12-26 21:13:33,838 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57253)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:13:33,838 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703614413.343182, 'user': {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 21:13:33,839 DEBUG core.py Start auth process for {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 21:13:33,846 DEBUG core.py Correct username, starting passwd check.
2023-12-26 21:13:33,846 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57253)>, {'response': 511, 'bin': '4e34b4ebd94c02f7e4f560b027d4b7fedb09af9ff28af0278e7fcc674edc6f854c9fddf04b7d84b2c2841203da027bdb650a25a4937139fd9605e7593272060c'}) , {}. Вызов из модуля core.utils
2023-12-26 21:13:33,847 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57253)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:13:33,848 DEBUG core.py Auth message = {'response': 511, 'bin': '4e34b4ebd94c02f7e4f560b027d4b7fedb09af9ff28af0278e7fcc674edc6f854c9fddf04b7d84b2c2841203da027bdb650a25a4937139fd9605e7593272060c'}
2023-12-26 21:13:33,848 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57253)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 21:13:34,358 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57253)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:13:34,358 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703614413.848544, 'account_name': 'qwer'}
2023-12-26 21:13:34,362 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57253)>, {'response': 202, 'data_list': ['qwer']}) , {}. Вызов из модуля core.utils
2023-12-26 21:13:34,863 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57253)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:13:34,864 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/core.py", line 97, in run
    self.process_client_message(get_message(client_with_message), client_with_message)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/logs/logger.py", line 44, in log_saver
    ret = func_to_log(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/core/utils.py", line 19, in get_message
    response = json.loads(json_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/.pyenv/versions/3.11.2/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/.pyenv/versions/3.11.2/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/.pyenv/versions/3.11.2/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-26 21:13:34,867 INFO core.py Клиент ('127.0.0.1', 57253) отключился от сервера.
2023-12-26 21:16:29,683 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57314)
2023-12-26 21:16:30,184 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:16:30,184 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703614589.689323, 'user': {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 21:16:30,185 DEBUG core.py Start auth process for {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 21:16:30,187 DEBUG core.py Correct username, starting passwd check.
2023-12-26 21:16:30,188 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 511, 'bin': '76ac7a30f4b32b974fc0013d26c46447c06a224227595f1073bc69e29c5a8c0d90b515891f268e564a18b733863f3d54e57290fb38433efc7ff7a6a2b50935aa'}) , {}. Вызов из модуля core.utils
2023-12-26 21:16:30,188 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:16:30,189 DEBUG core.py Auth message = {'response': 511, 'bin': '76ac7a30f4b32b974fc0013d26c46447c06a224227595f1073bc69e29c5a8c0d90b515891f268e564a18b733863f3d54e57290fb38433efc7ff7a6a2b50935aa'}
2023-12-26 21:16:30,190 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 21:16:30,697 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:16:30,697 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703614590.1904519, 'account_name': 'qwer'}
2023-12-26 21:16:30,698 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 202, 'data_list': ['qwer']}) , {}. Вызов из модуля core.utils
2023-12-26 21:16:31,200 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:16:31,200 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1703614590.7075782, 'user': 'qwer'}
2023-12-26 21:16:31,207 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2023-12-26 21:17:00,140 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 205}) , {}. Вызов из модуля core.utils
2023-12-26 21:17:00,771 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:17:00,771 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703614620.443728, 'account_name': 'qwer'}
2023-12-26 21:17:00,772 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 202, 'data_list': ['qwer', 'rewq']}) , {}. Вызов из модуля core.utils
2023-12-26 21:17:01,273 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:17:01,273 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1703614620.778259, 'user': 'qwer'}
2023-12-26 21:17:01,274 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2023-12-26 21:17:41,075 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57364)
2023-12-26 21:17:41,576 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57364)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:17:41,577 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703614661.0807528, 'user': {'account_name': 'rewq', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjpa7hRGFmv2+0+zs4sIr\nKyxBhoxzjWEHDyUXdP5kaKxQuQP3H68JhyqR5Pi0RuuNmu/f5FdIWn/ANMyEp47a\n6+UTT4H7uRA6SUrnC7tejWg61QxfIdnNsNTdWZbq1AtiMnIgxiRiDH2uI5ecrtd3\nl53RiU2ngHd+z7j6IBTfPrdk/NlZwv0xtncmA7+FyIJlxshrc6f+Ok6vQs09N7My\nSK/fSuU2a1GezDl1vWi1mfyWfX8STxCfTi0875iPQXvw4EQBCVxx1zOxARM0HJ6B\nJ7Psk+p70talJXk5ZlhpY+80BMBP1GCKnATu6aGPZL4kHkCuusJ940aVqhmJVmTt\nbQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 21:17:41,577 DEBUG core.py Start auth process for {'account_name': 'rewq', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjpa7hRGFmv2+0+zs4sIr\nKyxBhoxzjWEHDyUXdP5kaKxQuQP3H68JhyqR5Pi0RuuNmu/f5FdIWn/ANMyEp47a\n6+UTT4H7uRA6SUrnC7tejWg61QxfIdnNsNTdWZbq1AtiMnIgxiRiDH2uI5ecrtd3\nl53RiU2ngHd+z7j6IBTfPrdk/NlZwv0xtncmA7+FyIJlxshrc6f+Ok6vQs09N7My\nSK/fSuU2a1GezDl1vWi1mfyWfX8STxCfTi0875iPQXvw4EQBCVxx1zOxARM0HJ6B\nJ7Psk+p70talJXk5ZlhpY+80BMBP1GCKnATu6aGPZL4kHkCuusJ940aVqhmJVmTt\nbQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 21:17:41,580 DEBUG core.py Correct username, starting passwd check.
2023-12-26 21:17:41,581 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57364)>, {'response': 511, 'bin': '3b55a466ae3ba786e0ab3d1a379483827640e00b55dd7540138f39fcc1e8ff199a10db6aa2a432d0b13e837c2898bc6bb59f50c80a0cf1689aab0ea18212b1f8'}) , {}. Вызов из модуля core.utils
2023-12-26 21:17:41,581 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57364)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:17:41,583 DEBUG core.py Auth message = {'response': 511, 'bin': '3b55a466ae3ba786e0ab3d1a379483827640e00b55dd7540138f39fcc1e8ff199a10db6aa2a432d0b13e837c2898bc6bb59f50c80a0cf1689aab0ea18212b1f8'}
2023-12-26 21:17:41,583 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57364)>, {'response': 400, 'error': 'Неверный пароль.'}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:02,782 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57383)
2023-12-26 21:18:03,285 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57383)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:03,285 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703614682.78928, 'user': {'account_name': 'rewq', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjpa7hRGFmv2+0+zs4sIr\nKyxBhoxzjWEHDyUXdP5kaKxQuQP3H68JhyqR5Pi0RuuNmu/f5FdIWn/ANMyEp47a\n6+UTT4H7uRA6SUrnC7tejWg61QxfIdnNsNTdWZbq1AtiMnIgxiRiDH2uI5ecrtd3\nl53RiU2ngHd+z7j6IBTfPrdk/NlZwv0xtncmA7+FyIJlxshrc6f+Ok6vQs09N7My\nSK/fSuU2a1GezDl1vWi1mfyWfX8STxCfTi0875iPQXvw4EQBCVxx1zOxARM0HJ6B\nJ7Psk+p70talJXk5ZlhpY+80BMBP1GCKnATu6aGPZL4kHkCuusJ940aVqhmJVmTt\nbQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 21:18:03,285 DEBUG core.py Start auth process for {'account_name': 'rewq', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjpa7hRGFmv2+0+zs4sIr\nKyxBhoxzjWEHDyUXdP5kaKxQuQP3H68JhyqR5Pi0RuuNmu/f5FdIWn/ANMyEp47a\n6+UTT4H7uRA6SUrnC7tejWg61QxfIdnNsNTdWZbq1AtiMnIgxiRiDH2uI5ecrtd3\nl53RiU2ngHd+z7j6IBTfPrdk/NlZwv0xtncmA7+FyIJlxshrc6f+Ok6vQs09N7My\nSK/fSuU2a1GezDl1vWi1mfyWfX8STxCfTi0875iPQXvw4EQBCVxx1zOxARM0HJ6B\nJ7Psk+p70talJXk5ZlhpY+80BMBP1GCKnATu6aGPZL4kHkCuusJ940aVqhmJVmTt\nbQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 21:18:03,290 DEBUG core.py Correct username, starting passwd check.
2023-12-26 21:18:03,290 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57383)>, {'response': 511, 'bin': '01765fdca8aa99583819231b05113de250b8afa9673c6ab2fa78761f1e453df05559f8bbbc4a6b09d03f372865d70826f60c6bf69e3db12e70c5ee1073352fde'}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:03,290 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57383)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:03,292 DEBUG core.py Auth message = {'response': 511, 'bin': '01765fdca8aa99583819231b05113de250b8afa9673c6ab2fa78761f1e453df05559f8bbbc4a6b09d03f372865d70826f60c6bf69e3db12e70c5ee1073352fde'}
2023-12-26 21:18:03,292 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57383)>, {'response': 400, 'error': 'Неверный пароль.'}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:15,668 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57385)
2023-12-26 21:18:16,170 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57385)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:16,170 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703614695.6750479, 'user': {'account_name': 'rewq', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjpa7hRGFmv2+0+zs4sIr\nKyxBhoxzjWEHDyUXdP5kaKxQuQP3H68JhyqR5Pi0RuuNmu/f5FdIWn/ANMyEp47a\n6+UTT4H7uRA6SUrnC7tejWg61QxfIdnNsNTdWZbq1AtiMnIgxiRiDH2uI5ecrtd3\nl53RiU2ngHd+z7j6IBTfPrdk/NlZwv0xtncmA7+FyIJlxshrc6f+Ok6vQs09N7My\nSK/fSuU2a1GezDl1vWi1mfyWfX8STxCfTi0875iPQXvw4EQBCVxx1zOxARM0HJ6B\nJ7Psk+p70talJXk5ZlhpY+80BMBP1GCKnATu6aGPZL4kHkCuusJ940aVqhmJVmTt\nbQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 21:18:16,170 DEBUG core.py Start auth process for {'account_name': 'rewq', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjpa7hRGFmv2+0+zs4sIr\nKyxBhoxzjWEHDyUXdP5kaKxQuQP3H68JhyqR5Pi0RuuNmu/f5FdIWn/ANMyEp47a\n6+UTT4H7uRA6SUrnC7tejWg61QxfIdnNsNTdWZbq1AtiMnIgxiRiDH2uI5ecrtd3\nl53RiU2ngHd+z7j6IBTfPrdk/NlZwv0xtncmA7+FyIJlxshrc6f+Ok6vQs09N7My\nSK/fSuU2a1GezDl1vWi1mfyWfX8STxCfTi0875iPQXvw4EQBCVxx1zOxARM0HJ6B\nJ7Psk+p70talJXk5ZlhpY+80BMBP1GCKnATu6aGPZL4kHkCuusJ940aVqhmJVmTt\nbQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 21:18:16,172 DEBUG core.py Correct username, starting passwd check.
2023-12-26 21:18:16,172 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57385)>, {'response': 511, 'bin': 'e053c1f77dad37a3c0304e4d632a2de781bf5292893a16e273114555a18b45759af622671f717eb10908fd783527cc7d4fd4ca10878db05f4755ca5fda86dd6b'}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:16,173 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57385)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:16,174 DEBUG core.py Auth message = {'response': 511, 'bin': 'e053c1f77dad37a3c0304e4d632a2de781bf5292893a16e273114555a18b45759af622671f717eb10908fd783527cc7d4fd4ca10878db05f4755ca5fda86dd6b'}
2023-12-26 21:18:16,174 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57385)>, {'response': 400, 'error': 'Неверный пароль.'}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:27,200 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 205}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:28,197 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:28,198 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703614708.044508, 'account_name': 'qwer'}
2023-12-26 21:18:28,199 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:28,700 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:28,700 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1703614708.211051, 'user': 'qwer'}
2023-12-26 21:18:28,702 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:33,307 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57389)
2023-12-26 21:18:33,808 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57389)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:33,809 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703614713.313622, 'user': {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fuQ7TRZuul+0RJvA5VW\nZLteNIkvlusnGgSn1rgAwS4jiS2uSvJ3gv07YrrCGxDtD3hPwMyTyzv+oiNGyfIG\nvtZfum4QPtDGkn3kiNZXF/Xf7BR2TcazpXLF53sOxxt/cV7gvHHNCAlRfU4LHWP5\nmY7KILz267QbcywHIlb1AxBhq4dyymfpovO/iz3FljXhJdImM+xmZBQVVjquSZLU\n4pf3dwBjyU6wSopXmN4UAGbjjbBFhPlrKuam/Ovzesx7Ai3+AO9+eIbE/tVKi06U\n7TvUIQ53ERBhgr7sgXOrlHoTs5It77jybwB7E8td3aJaJiy+vYmuUtxe15lsrRoi\nrQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 21:18:33,809 DEBUG core.py Start auth process for {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fuQ7TRZuul+0RJvA5VW\nZLteNIkvlusnGgSn1rgAwS4jiS2uSvJ3gv07YrrCGxDtD3hPwMyTyzv+oiNGyfIG\nvtZfum4QPtDGkn3kiNZXF/Xf7BR2TcazpXLF53sOxxt/cV7gvHHNCAlRfU4LHWP5\nmY7KILz267QbcywHIlb1AxBhq4dyymfpovO/iz3FljXhJdImM+xmZBQVVjquSZLU\n4pf3dwBjyU6wSopXmN4UAGbjjbBFhPlrKuam/Ovzesx7Ai3+AO9+eIbE/tVKi06U\n7TvUIQ53ERBhgr7sgXOrlHoTs5It77jybwB7E8td3aJaJiy+vYmuUtxe15lsrRoi\nrQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 21:18:33,813 DEBUG core.py Correct username, starting passwd check.
2023-12-26 21:18:33,813 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57389)>, {'response': 511, 'bin': '2cdaf6bb2431b9d9b1b3e6fc3e6b65ba19eab03b87d74b3fff1b781638578364a95289d2bf348288b827c8098d28a5cdd17a2fbb799080438bb57ce01a0aa610'}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:33,814 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57389)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:33,815 DEBUG core.py Auth message = {'response': 511, 'bin': '2cdaf6bb2431b9d9b1b3e6fc3e6b65ba19eab03b87d74b3fff1b781638578364a95289d2bf348288b827c8098d28a5cdd17a2fbb799080438bb57ce01a0aa610'}
2023-12-26 21:18:33,815 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57389)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:34,322 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57389)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:34,322 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703614713.816288, 'account_name': 'new'}
2023-12-26 21:18:34,322 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57389)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:34,824 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57389)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:34,824 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1703614714.33162, 'user': 'new'}
2023-12-26 21:18:34,825 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57389)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:43,845 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:43,845 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1703614723.527573, 'user': 'qwer', 'account_name': 'new'}
2023-12-26 21:18:43,859 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:49,872 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:49,872 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703614729.7856908, 'account_name': 'qwer'}
2023-12-26 21:18:49,874 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:51,377 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:51,378 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703614730.9338481, 'account_name': 'qwer'}
2023-12-26 21:18:51,380 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:52,884 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:52,884 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703614732.6384902, 'account_name': 'qwer'}
2023-12-26 21:18:52,886 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:53,388 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:53,389 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703614732.9052968, 'account_name': 'qwer'}
2023-12-26 21:18:53,391 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:53,892 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:53,893 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703614733.402409, 'account_name': 'qwer'}
2023-12-26 21:18:53,895 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 21:18:54,898 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:18:54,898 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1703614733.910502, 'user': 'qwer', 'account_name': 'rewq'}
2023-12-26 21:18:54,906 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 21:19:05,931 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57314)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:19:05,936 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1703614745.744889, 'account_name': 'rewq'}
2023-12-26 21:24:01,961 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 21:24:01,961 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 21:24:01,961 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 21:24:01,961 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 21:24:01,962 DEBUG server.py Аргументы успешно загружены.
2023-12-26 21:24:01,962 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 21:24:26,073 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57508)
2023-12-26 21:24:26,575 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57508)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:24:26,576 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703615066.079892, 'user': {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 21:24:26,576 DEBUG core.py Start auth process for {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 21:24:26,583 DEBUG core.py Correct username, starting passwd check.
2023-12-26 21:24:26,583 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57508)>, {'response': 511, 'bin': '01469c421f522a3623da701372cdc2fe692f2dab2199cecc3ebb8044ec980348ffc3dc9404dc4e133c902c1cfe81a1f03a9fe4cf1f0e75e4709b4309e69a4c8e'}) , {}. Вызов из модуля core.utils
2023-12-26 21:24:26,583 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57508)>,) , {}. Вызов из модуля core.utils
2023-12-26 21:24:26,585 DEBUG core.py Auth message = {'response': 511, 'bin': '01469c421f522a3623da701372cdc2fe692f2dab2199cecc3ebb8044ec980348ffc3dc9404dc4e133c902c1cfe81a1f03a9fe4cf1f0e75e4709b4309e69a4c8e'}
2023-12-26 21:24:26,585 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57508)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:36:01,458 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 22:36:01,459 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 22:36:01,459 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 22:36:01,459 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 22:36:01,460 DEBUG server.py Аргументы успешно загружены.
2023-12-26 22:36:01,461 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 22:36:25,445 INFO core.py Установлено соедение с ПК ('127.0.0.1', 58333)
2023-12-26 22:36:25,947 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58333)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:36:25,948 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703619385.4545228, 'user': {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 22:36:25,948 DEBUG core.py Start auth process for {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 22:36:25,955 DEBUG core.py Correct username, starting passwd check.
2023-12-26 22:36:25,955 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58333)>, {'response': 511, 'bin': '339d353e7e4d12a56535f32cc46f2d9f6b7a8d8174de198959d2ebbc261871edc6d6d3fe5e96f549f3545f34625f83b0aa693a2537529b06e35f48fd0371e7d0'}) , {}. Вызов из модуля core.utils
2023-12-26 22:36:25,955 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58333)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:36:25,957 DEBUG core.py Auth message = {'response': 511, 'bin': '339d353e7e4d12a56535f32cc46f2d9f6b7a8d8174de198959d2ebbc261871edc6d6d3fe5e96f549f3545f34625f83b0aa693a2537529b06e35f48fd0371e7d0'}
2023-12-26 22:36:25,957 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58333)>, {'response': 400, 'error': 'Неверный пароль.'}) , {}. Вызов из модуля core.utils
2023-12-26 22:36:42,877 INFO core.py Установлено соедение с ПК ('127.0.0.1', 58347)
2023-12-26 22:36:43,378 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:36:43,379 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703619402.886251, 'user': {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 22:36:43,379 DEBUG core.py Start auth process for {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 22:36:43,383 DEBUG core.py Correct username, starting passwd check.
2023-12-26 22:36:43,383 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 511, 'bin': '2299149743451d2b547648c90abd13e6f37707f3234bc297223447030cb3684adec813b786eed1f9c108fa4cf88e27bbd637e8160ddec28992d6aa6f110dea8a'}) , {}. Вызов из модуля core.utils
2023-12-26 22:36:43,383 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:36:43,386 DEBUG core.py Auth message = {'response': 511, 'bin': '2299149743451d2b547648c90abd13e6f37707f3234bc297223447030cb3684adec813b786eed1f9c108fa4cf88e27bbd637e8160ddec28992d6aa6f110dea8a'}
2023-12-26 22:36:43,386 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:36:43,896 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:36:43,896 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703619403.386703, 'account_name': 'qwer'}
2023-12-26 22:36:43,897 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 22:36:44,398 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:36:44,399 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1703619403.9078112, 'user': 'qwer'}
2023-12-26 22:36:44,405 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 202, 'data_list': ['new', 'rewq']}) , {}. Вызов из модуля core.utils
2023-12-26 22:37:21,445 INFO core.py Установлено соедение с ПК ('127.0.0.1', 58357)
2023-12-26 22:37:21,946 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:37:21,947 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703619441.453986, 'user': {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fuQ7TRZuul+0RJvA5VW\nZLteNIkvlusnGgSn1rgAwS4jiS2uSvJ3gv07YrrCGxDtD3hPwMyTyzv+oiNGyfIG\nvtZfum4QPtDGkn3kiNZXF/Xf7BR2TcazpXLF53sOxxt/cV7gvHHNCAlRfU4LHWP5\nmY7KILz267QbcywHIlb1AxBhq4dyymfpovO/iz3FljXhJdImM+xmZBQVVjquSZLU\n4pf3dwBjyU6wSopXmN4UAGbjjbBFhPlrKuam/Ovzesx7Ai3+AO9+eIbE/tVKi06U\n7TvUIQ53ERBhgr7sgXOrlHoTs5It77jybwB7E8td3aJaJiy+vYmuUtxe15lsrRoi\nrQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 22:37:21,947 DEBUG core.py Start auth process for {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fuQ7TRZuul+0RJvA5VW\nZLteNIkvlusnGgSn1rgAwS4jiS2uSvJ3gv07YrrCGxDtD3hPwMyTyzv+oiNGyfIG\nvtZfum4QPtDGkn3kiNZXF/Xf7BR2TcazpXLF53sOxxt/cV7gvHHNCAlRfU4LHWP5\nmY7KILz267QbcywHIlb1AxBhq4dyymfpovO/iz3FljXhJdImM+xmZBQVVjquSZLU\n4pf3dwBjyU6wSopXmN4UAGbjjbBFhPlrKuam/Ovzesx7Ai3+AO9+eIbE/tVKi06U\n7TvUIQ53ERBhgr7sgXOrlHoTs5It77jybwB7E8td3aJaJiy+vYmuUtxe15lsrRoi\nrQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 22:37:21,950 DEBUG core.py Correct username, starting passwd check.
2023-12-26 22:37:21,950 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'response': 511, 'bin': '979668d10e9880b29a66ddfe8de356eca5044dc3491aa6f2ef57e5954b47fae86f4a18b931b954fea7d709aaf36283e35e183097d7c6c09e850e089ff1d1593e'}) , {}. Вызов из модуля core.utils
2023-12-26 22:37:21,951 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:37:21,952 DEBUG core.py Auth message = {'response': 511, 'bin': '979668d10e9880b29a66ddfe8de356eca5044dc3491aa6f2ef57e5954b47fae86f4a18b931b954fea7d709aaf36283e35e183097d7c6c09e850e089ff1d1593e'}
2023-12-26 22:37:21,953 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:37:22,460 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:37:22,460 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703619441.953504, 'account_name': 'new'}
2023-12-26 22:37:22,462 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 22:37:22,963 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:37:22,964 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1703619442.472588, 'user': 'new'}
2023-12-26 22:37:22,968 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2023-12-26 22:37:28,480 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:37:28,481 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1703619448.0002391, 'user': 'new', 'account_name': 'qwer'}
2023-12-26 22:37:28,498 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:37:37,018 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:37:37,018 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1703619456.921364, 'account_name': 'qwer'}
2023-12-26 22:37:37,021 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}) , {}. Вызов из модуля core.utils
2023-12-26 22:37:47,554 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:37:47,555 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'new', 'to': 'qwer', 'time': 1703619466.752535, 'mess_text': 'P5l5nMChGrexsAv2J0Ul1aWyOwk2k1j3RGiN1ueDEo8aGWUXx9yn4BKeqPeZ3tmmphZbOkgWMhFfcEFo8xTxib9twIXGpULgSblrfoNV512dO7mW+NLolLy44MllRAozv+81V6+UMvAyJZGvAKxynKZKC/Y4qAqfQR6JFkxxKNbAti/TxwRS727FkrOTUQSdc4wypJXc6zB+MslsZh4tHyw6lM5j/wkFEKi3KRAgr3ICp06u0h7tmeO01dx1WfLISO7ADB0/9BgS0rYXwTlY3DXdqL7dEQMsAZTseHQK8HAJbZkIjayodwMwzQHalXsQA2y3v9/dRoJJH2zJUzHzbw=='}
2023-12-26 22:37:47,565 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'action': 'message', 'from': 'new', 'to': 'qwer', 'time': 1703619466.752535, 'mess_text': 'P5l5nMChGrexsAv2J0Ul1aWyOwk2k1j3RGiN1ueDEo8aGWUXx9yn4BKeqPeZ3tmmphZbOkgWMhFfcEFo8xTxib9twIXGpULgSblrfoNV512dO7mW+NLolLy44MllRAozv+81V6+UMvAyJZGvAKxynKZKC/Y4qAqfQR6JFkxxKNbAti/TxwRS727FkrOTUQSdc4wypJXc6zB+MslsZh4tHyw6lM5j/wkFEKi3KRAgr3ICp06u0h7tmeO01dx1WfLISO7ADB0/9BgS0rYXwTlY3DXdqL7dEQMsAZTseHQK8HAJbZkIjayodwMwzQHalXsQA2y3v9/dRoJJH2zJUzHzbw=='}) , {}. Вызов из модуля core.utils
2023-12-26 22:37:47,565 INFO core.py Отправлено сообщение пользователю qwer от пользователя new.
2023-12-26 22:37:47,565 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:37:58,587 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:37:58,589 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1703619478.191872, 'account_name': 'new'}
2023-12-26 22:37:58,593 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fuQ7TRZuul+0RJvA5VW\nZLteNIkvlusnGgSn1rgAwS4jiS2uSvJ3gv07YrrCGxDtD3hPwMyTyzv+oiNGyfIG\nvtZfum4QPtDGkn3kiNZXF/Xf7BR2TcazpXLF53sOxxt/cV7gvHHNCAlRfU4LHWP5\nmY7KILz267QbcywHIlb1AxBhq4dyymfpovO/iz3FljXhJdImM+xmZBQVVjquSZLU\n4pf3dwBjyU6wSopXmN4UAGbjjbBFhPlrKuam/Ovzesx7Ai3+AO9+eIbE/tVKi06U\n7TvUIQ53ERBhgr7sgXOrlHoTs5It77jybwB7E8td3aJaJiy+vYmuUtxe15lsrRoi\nrQIDAQAB\n-----END PUBLIC KEY-----'}) , {}. Вызов из модуля core.utils
2023-12-26 22:38:09,118 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:38:09,119 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1703619488.439855, 'account_name': 'new'}
2023-12-26 22:38:09,122 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fuQ7TRZuul+0RJvA5VW\nZLteNIkvlusnGgSn1rgAwS4jiS2uSvJ3gv07YrrCGxDtD3hPwMyTyzv+oiNGyfIG\nvtZfum4QPtDGkn3kiNZXF/Xf7BR2TcazpXLF53sOxxt/cV7gvHHNCAlRfU4LHWP5\nmY7KILz267QbcywHIlb1AxBhq4dyymfpovO/iz3FljXhJdImM+xmZBQVVjquSZLU\n4pf3dwBjyU6wSopXmN4UAGbjjbBFhPlrKuam/Ovzesx7Ai3+AO9+eIbE/tVKi06U\n7TvUIQ53ERBhgr7sgXOrlHoTs5It77jybwB7E8td3aJaJiy+vYmuUtxe15lsrRoi\nrQIDAQAB\n-----END PUBLIC KEY-----'}) , {}. Вызов из модуля core.utils
2023-12-26 22:38:20,146 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:38:20,147 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'qwer', 'to': 'new', 'time': 1703619500.017778, 'mess_text': 'NQUHF57XH/Xa558g3GD8V3SvGyPnMKK4QMjXWPW6XJNVCvz7a1yGt8frRq+Yrl4yEUiFm1jjATC97lnfyIY8crJD44F+v2F03j6aqrD6raX2xDqiYx4h/FszzkckUUEktAwU8QAVtT1XXDEMXfHhSIPim0qHbo/8hyi1BtVz2HPTixSQ+E3FF6XHyRde/vZzY07UZfJEhNoSsR5/M3O0zWA6OguX1WaP2oczZn/Bagl5hmkfijvyYPHxXCcJgOQFnHeoCdbtGrxVIaSIPo7H+JkghofrhmM+SSAhu8piOyx4wEg5j0oWh84LMtgqx1E5vNEqKxZDNejJXUkXwm2w8A=='}
2023-12-26 22:38:20,158 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'action': 'message', 'from': 'qwer', 'to': 'new', 'time': 1703619500.017778, 'mess_text': 'NQUHF57XH/Xa558g3GD8V3SvGyPnMKK4QMjXWPW6XJNVCvz7a1yGt8frRq+Yrl4yEUiFm1jjATC97lnfyIY8crJD44F+v2F03j6aqrD6raX2xDqiYx4h/FszzkckUUEktAwU8QAVtT1XXDEMXfHhSIPim0qHbo/8hyi1BtVz2HPTixSQ+E3FF6XHyRde/vZzY07UZfJEhNoSsR5/M3O0zWA6OguX1WaP2oczZn/Bagl5hmkfijvyYPHxXCcJgOQFnHeoCdbtGrxVIaSIPo7H+JkghofrhmM+SSAhu8piOyx4wEg5j0oWh84LMtgqx1E5vNEqKxZDNejJXUkXwm2w8A=='}) , {}. Вызов из модуля core.utils
2023-12-26 22:38:20,158 INFO core.py Отправлено сообщение пользователю new от пользователя qwer.
2023-12-26 22:38:20,158 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:38:46,214 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:38:46,215 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'new', 'to': 'qwer', 'time': 1703619525.905416, 'mess_text': 'SgYM0WCmhY5xY6F6lCV1uCMrvK9UUU+y/lCNmKc7ymKwvUbXPjpTt7SHtNj7okkEHIj8HOb9Nir7k0weme2WpFAB9gCaMbmke7+lNf1oyJqNV4dMCRZsk29Fj3Sk2/2+fE1uH4CpFUKNb89Y2844BOBYVlRBXRIqwXeWk42ZcBp+oRV44mzjwmgeW3B0byD5JkbsA4JMEyq/I15cSyhXlaOU80jmSHpm21FokOjsEbVfvCfGZGwWjmQBiBKllEk/hp1iYbdN37a5fnxpcmMdBFhCtxEau0qCtUTrdvTkqRjnaYIknGIlfOW5jcKwghx2c2S4DPlDSmqhfX0FHGr8BA=='}
2023-12-26 22:38:46,224 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'action': 'message', 'from': 'new', 'to': 'qwer', 'time': 1703619525.905416, 'mess_text': 'SgYM0WCmhY5xY6F6lCV1uCMrvK9UUU+y/lCNmKc7ymKwvUbXPjpTt7SHtNj7okkEHIj8HOb9Nir7k0weme2WpFAB9gCaMbmke7+lNf1oyJqNV4dMCRZsk29Fj3Sk2/2+fE1uH4CpFUKNb89Y2844BOBYVlRBXRIqwXeWk42ZcBp+oRV44mzjwmgeW3B0byD5JkbsA4JMEyq/I15cSyhXlaOU80jmSHpm21FokOjsEbVfvCfGZGwWjmQBiBKllEk/hp1iYbdN37a5fnxpcmMdBFhCtxEau0qCtUTrdvTkqRjnaYIknGIlfOW5jcKwghx2c2S4DPlDSmqhfX0FHGr8BA=='}) , {}. Вызов из модуля core.utils
2023-12-26 22:38:46,224 INFO core.py Отправлено сообщение пользователю qwer от пользователя new.
2023-12-26 22:38:46,225 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:38:54,744 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:38:54,745 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'qwer', 'to': 'new', 'time': 1703619534.466327, 'mess_text': 'QUulQ0MLgqIcv/gvO3Wk8d9c3TvJHPCAFnwt+/DOZcyNAXiA9zU/663JYK24xrg1hddvd5dqg7KL1ZsWUJQNoD8UrNuWXuEeQpUQ9Kua/+rmDiIlEmfA/H3m75z7xOhsSAA07s8QYzs9xDo+4pZUnFJtMELLULhCbgNKRI5zoHOmZY0emCkqB022h2/77g2lo2YI7COeVD7Wy+bbKutwX34rMRlD1zeWkhYCPfrvAezmi0u3okW7pwXKx33DK4fTiS3YqlMhVVkImOZN/KgPbsgG56UoVzGUCzn68aBprJM/OZ+5tGkloxxMYYAR1kmR5GtLFzhCrvqiaVwiHGdaeA=='}
2023-12-26 22:38:54,754 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'action': 'message', 'from': 'qwer', 'to': 'new', 'time': 1703619534.466327, 'mess_text': 'QUulQ0MLgqIcv/gvO3Wk8d9c3TvJHPCAFnwt+/DOZcyNAXiA9zU/663JYK24xrg1hddvd5dqg7KL1ZsWUJQNoD8UrNuWXuEeQpUQ9Kua/+rmDiIlEmfA/H3m75z7xOhsSAA07s8QYzs9xDo+4pZUnFJtMELLULhCbgNKRI5zoHOmZY0emCkqB022h2/77g2lo2YI7COeVD7Wy+bbKutwX34rMRlD1zeWkhYCPfrvAezmi0u3okW7pwXKx33DK4fTiS3YqlMhVVkImOZN/KgPbsgG56UoVzGUCzn68aBprJM/OZ+5tGkloxxMYYAR1kmR5GtLFzhCrvqiaVwiHGdaeA=='}) , {}. Вызов из модуля core.utils
2023-12-26 22:38:54,755 INFO core.py Отправлено сообщение пользователю new от пользователя qwer.
2023-12-26 22:38:54,755 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:39:13,130 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:39:13,131 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'qwer', 'to': 'new', 'time': 1703619552.7634308, 'mess_text': 'YfHC28Dq1HZs5BwQYdzlYL4WFL2M5LOzJiVlLUIZgTXF1VxrG+8LA+tBtj16E8HVQKb6i1+BplnKOLH8dhGSegtFpeH3CRJ5uq3xRaK/BhIC/G9DiOuPNJ3iVVK6QROM/2rzWQ4iE0DrBFkma2L4LaiGbKp7EyEiLD4F8nrsYmkfC0/GU2UR8oka4nIYNFOKnTunaISY3mTR92YpJY8gpUgwykyQ2FcyD7fMSWGPWp6Xfsk3ySCcL79iihCqpS20k38VZb+lJayLOy/0RxrvJk4zm6yXGV5MFCfCy1vl6NlogNf2oMEMPEp+Bp723Y48A0P/jSfLDRAfqAa3UryGvw=='}
2023-12-26 22:39:13,141 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'action': 'message', 'from': 'qwer', 'to': 'new', 'time': 1703619552.7634308, 'mess_text': 'YfHC28Dq1HZs5BwQYdzlYL4WFL2M5LOzJiVlLUIZgTXF1VxrG+8LA+tBtj16E8HVQKb6i1+BplnKOLH8dhGSegtFpeH3CRJ5uq3xRaK/BhIC/G9DiOuPNJ3iVVK6QROM/2rzWQ4iE0DrBFkma2L4LaiGbKp7EyEiLD4F8nrsYmkfC0/GU2UR8oka4nIYNFOKnTunaISY3mTR92YpJY8gpUgwykyQ2FcyD7fMSWGPWp6Xfsk3ySCcL79iihCqpS20k38VZb+lJayLOy/0RxrvJk4zm6yXGV5MFCfCy1vl6NlogNf2oMEMPEp+Bp723Y48A0P/jSfLDRAfqAa3UryGvw=='}) , {}. Вызов из модуля core.utils
2023-12-26 22:39:13,141 INFO core.py Отправлено сообщение пользователю new от пользователя qwer.
2023-12-26 22:39:13,141 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:39:29,177 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:39:29,178 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'new', 'to': 'qwer', 'time': 1703619568.863456, 'mess_text': 'lXRbrStxeJNWNIp9BZmXJuUeWaIJ9w/KMmQNYSuRON0Zh9C8HyB58pZYoUo/nzPByo1vSwmDQBhI44XJd69SgRDv34/3m1xpeM7pWP0hVtHfzgbarTqgJrK/vv8fdceaD0sL7Oxk9uY4fAHdhlgw6K59pvNRmEzImBqX+cX9M2ROYwKnWLMW0BXyPVBBiiJMjUrOV/tKP83/ypyn3rZnEU/5JyzhSQcCVXIgAxvjAQiBruEVe4ovTMuqFgO75w2G4Fp4YbhpbhV1xhINHCFjTJOYiJ9RLM6Pr9P7GxAJ8IF5xh6FDpryLP5Q0Uo0IKRa2HRfv4W+DBTOGoSbvEEwUw=='}
2023-12-26 22:39:29,188 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'action': 'message', 'from': 'new', 'to': 'qwer', 'time': 1703619568.863456, 'mess_text': 'lXRbrStxeJNWNIp9BZmXJuUeWaIJ9w/KMmQNYSuRON0Zh9C8HyB58pZYoUo/nzPByo1vSwmDQBhI44XJd69SgRDv34/3m1xpeM7pWP0hVtHfzgbarTqgJrK/vv8fdceaD0sL7Oxk9uY4fAHdhlgw6K59pvNRmEzImBqX+cX9M2ROYwKnWLMW0BXyPVBBiiJMjUrOV/tKP83/ypyn3rZnEU/5JyzhSQcCVXIgAxvjAQiBruEVe4ovTMuqFgO75w2G4Fp4YbhpbhV1xhINHCFjTJOYiJ9RLM6Pr9P7GxAJ8IF5xh6FDpryLP5Q0Uo0IKRa2HRfv4W+DBTOGoSbvEEwUw=='}) , {}. Вызов из модуля core.utils
2023-12-26 22:39:29,188 INFO core.py Отправлено сообщение пользователю qwer от пользователя new.
2023-12-26 22:39:29,188 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:39:44,722 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:39:44,723 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1703619584.636628, 'account_name': 'qwer'}
2023-12-26 22:39:44,726 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnXwJ/rnIRh0lwvTdlrX\nL2uNLX75NMXkKfC9eMr5IEflw3rVtAN+UoXHrPargAjoknCjyJnmCPccziIp2zmv\njOcN977dVldqrQOFSMxien1yJk6sV5l3+U5med11acsP2MEmU25PNXhian+ZWxcL\nvjMp+mdfhfpJoxwQ220A/AJ+0tbb1j9vYXa2YWbQUjLS/rxZlWBTvKhlCJzeRShj\nkJ3r/tJTmaeijg3LDmZEa+zgYDswAPVeb7Fn8uLxUCxzrcaYOKrVhIwbMwSQKbX1\nFue1kJdloB9GY3nONBYmEvV34MHT5mvuyAgbrZsgDp6LfhR5icGgcwWo5lwtjnvz\nXwIDAQAB\n-----END PUBLIC KEY-----'}) , {}. Вызов из модуля core.utils
2023-12-26 22:39:55,751 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:39:55,751 DEBUG core.py Разбор сообщения от клиента : {'action': 'remove', 'time': 1703619595.6448908, 'user': 'qwer', 'account_name': 'rewq'}
2023-12-26 22:39:55,761 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:40:12,298 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:40:12,298 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703619611.4839182, 'account_name': 'qwer'}
2023-12-26 22:40:12,300 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 22:40:49,960 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:40:49,962 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703619649.2489989, 'account_name': 'qwer'}
2023-12-26 22:40:49,964 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 22:40:52,971 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:40:52,972 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1703619652.265138, 'user': 'qwer', 'account_name': 'rewq'}
2023-12-26 22:40:52,982 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:40:58,996 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:40:58,997 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1703619658.6357892, 'account_name': 'rewq'}
2023-12-26 22:40:58,999 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 400, 'error': 'Нет публичного ключа для данного пользователя'}) , {}. Вызов из модуля core.utils
2023-12-26 22:41:09,525 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:41:09,526 DEBUG core.py Разбор сообщения от клиента : {'action': 'remove', 'time': 1703619669.148829, 'user': 'qwer', 'account_name': 'new'}
2023-12-26 22:41:09,534 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:41:16,052 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:41:16,053 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1703619675.9208488, 'account_name': 'rewq'}
2023-12-26 22:41:16,055 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 400, 'error': 'Нет публичного ключа для данного пользователя'}) , {}. Вызов из модуля core.utils
2023-12-26 22:41:20,566 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:41:20,567 DEBUG core.py Разбор сообщения от клиента : {'action': 'remove', 'time': 1703619680.491342, 'user': 'qwer', 'account_name': 'rewq'}
2023-12-26 22:41:20,574 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:41:29,091 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:41:29,091 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1703619688.140985, 'user': 'qwer', 'account_name': 'new'}
2023-12-26 22:41:29,098 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:41:34,109 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:41:34,110 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1703619693.7544682, 'account_name': 'new'}
2023-12-26 22:41:34,112 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fuQ7TRZuul+0RJvA5VW\nZLteNIkvlusnGgSn1rgAwS4jiS2uSvJ3gv07YrrCGxDtD3hPwMyTyzv+oiNGyfIG\nvtZfum4QPtDGkn3kiNZXF/Xf7BR2TcazpXLF53sOxxt/cV7gvHHNCAlRfU4LHWP5\nmY7KILz267QbcywHIlb1AxBhq4dyymfpovO/iz3FljXhJdImM+xmZBQVVjquSZLU\n4pf3dwBjyU6wSopXmN4UAGbjjbBFhPlrKuam/Ovzesx7Ai3+AO9+eIbE/tVKi06U\n7TvUIQ53ERBhgr7sgXOrlHoTs5It77jybwB7E8td3aJaJiy+vYmuUtxe15lsrRoi\nrQIDAQAB\n-----END PUBLIC KEY-----'}) , {}. Вызов из модуля core.utils
2023-12-26 22:42:02,172 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58347)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:42:02,172 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1703619721.8532732, 'account_name': 'qwer'}
2023-12-26 22:42:02,172 INFO core.py Клиент ('127.0.0.1', 58347) отключился от сервера.
2023-12-26 22:42:05,683 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=14, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58357)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:42:05,684 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1703619725.281576, 'account_name': 'new'}
2023-12-26 22:42:05,684 INFO core.py Клиент ('127.0.0.1', 58357) отключился от сервера.
2023-12-26 22:49:45,207 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 22:49:45,208 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 22:49:45,208 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 22:49:45,208 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 22:49:45,209 DEBUG server.py Аргументы успешно загружены.
2023-12-26 22:49:45,210 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 22:50:40,483 INFO core.py Установлено соедение с ПК ('127.0.0.1', 58780)
2023-12-26 22:50:40,985 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58780)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:50:40,986 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703620240.492032, 'user': {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiFl1DMQlrlQWYzAj80XQ\nR7vvAFUNyVg7N2onD7ZTxeqDtPP81/PlIV1V2+v3r6FGjpqpjt0+HQwxwu3ElXbe\nbd67x2d5wMI7Q7QiTXFr5Mf/zmReAabEhM2NGby6xQQWVo5uWzVlgk5cryvX92VA\nbdll6BXG8NP1HopO1FH4DF3TacXVJZyAjGvAsrczMDdd7zM7YuIOrZfipPVhoZnK\nBQ0ZWwl/bJQHZDG3q92tojztFegxhg5308C7XXxuJJPQvDF+y7uzEvgjhsxjanW9\nU/c2YCEN6eM8GiIf2k7de6mI3WzcHKvUEu83FBw9mNsvS+qkcdmf0wOn5CssEyaH\n5wIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 22:50:40,986 DEBUG core.py Start auth process for {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiFl1DMQlrlQWYzAj80XQ\nR7vvAFUNyVg7N2onD7ZTxeqDtPP81/PlIV1V2+v3r6FGjpqpjt0+HQwxwu3ElXbe\nbd67x2d5wMI7Q7QiTXFr5Mf/zmReAabEhM2NGby6xQQWVo5uWzVlgk5cryvX92VA\nbdll6BXG8NP1HopO1FH4DF3TacXVJZyAjGvAsrczMDdd7zM7YuIOrZfipPVhoZnK\nBQ0ZWwl/bJQHZDG3q92tojztFegxhg5308C7XXxuJJPQvDF+y7uzEvgjhsxjanW9\nU/c2YCEN6eM8GiIf2k7de6mI3WzcHKvUEu83FBw9mNsvS+qkcdmf0wOn5CssEyaH\n5wIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 22:50:40,994 DEBUG core.py Correct username, starting passwd check.
2023-12-26 22:50:40,994 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58780)>, {'response': 511, 'bin': '4f841b3c23a025031d193b990f9d184fb299f828e2c596e3b8e1e978107b46b7a94175fb0c13e109e72b5caea7fa118eb62ac3d7747dd7b88f7cacbd6f280741'}) , {}. Вызов из модуля core.utils
2023-12-26 22:50:40,994 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58780)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:50:40,996 DEBUG core.py Auth message = {'response': 511, 'bin': '4f841b3c23a025031d193b990f9d184fb299f828e2c596e3b8e1e978107b46b7a94175fb0c13e109e72b5caea7fa118eb62ac3d7747dd7b88f7cacbd6f280741'}
2023-12-26 22:50:40,996 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58780)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:50:41,506 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58780)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:50:41,506 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703620240.9963589, 'account_name': 'new'}
2023-12-26 22:50:41,507 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58780)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 22:50:42,009 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58780)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:50:42,009 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1703620241.5173519, 'user': 'new'}
2023-12-26 22:50:42,018 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=9, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58780)>, {'response': 202, 'data_list': ['qwer']}) , {}. Вызов из модуля core.utils
2023-12-26 22:51:20,793 INFO core.py Установлено соедение с ПК ('127.0.0.1', 58787)
2023-12-26 22:51:21,294 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=10, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58787)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:51:21,294 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703620280.801903, 'user': {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+MRLoOB0gkeMEbe2NNax\nVrA4UJrsbkLI/v1VOYUU39dF9iK6CdesSDvszA6ZhWlcqZk+pVigkjdd+rf/P4zb\nHPA4U8NYcA4+VSxvDlwfmleFySTwm96/GwvRpGfTuVZUbNpW0n5jBNGVk9RXNVu3\nlyXQz7Zi+8HzHqpXg1VjawWj9Kv1xPG1w+xrlssCkXT8/y+WxBG2ZkpJZhezdSIF\nXkNIbWhMLEUsOGcD3S89fHTXWsKqNKHlBinKaetRTQvRjJ3NY6zOyi/qRcPl+f3J\ndj2y1ug+sSbdYETnFIZ0dJ9jkkBeochpBCoL6pXTJGFooNrftgFsrHb5uLFfjhNr\nVQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 22:51:21,295 DEBUG core.py Start auth process for {'account_name': 'qwer', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+MRLoOB0gkeMEbe2NNax\nVrA4UJrsbkLI/v1VOYUU39dF9iK6CdesSDvszA6ZhWlcqZk+pVigkjdd+rf/P4zb\nHPA4U8NYcA4+VSxvDlwfmleFySTwm96/GwvRpGfTuVZUbNpW0n5jBNGVk9RXNVu3\nlyXQz7Zi+8HzHqpXg1VjawWj9Kv1xPG1w+xrlssCkXT8/y+WxBG2ZkpJZhezdSIF\nXkNIbWhMLEUsOGcD3S89fHTXWsKqNKHlBinKaetRTQvRjJ3NY6zOyi/qRcPl+f3J\ndj2y1ug+sSbdYETnFIZ0dJ9jkkBeochpBCoL6pXTJGFooNrftgFsrHb5uLFfjhNr\nVQIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 22:51:21,298 DEBUG core.py Correct username, starting passwd check.
2023-12-26 22:51:21,299 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=10, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58787)>, {'response': 511, 'bin': '8724d22a21adcef1d9f0978a9f5fc339252d5a5fa3739a2b92f54de0e3ee8fdf55879972ce1efaa760f7e9a7a1770673e1c4ff559fbd4778a058c7483370fbd6'}) , {}. Вызов из модуля core.utils
2023-12-26 22:51:21,299 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=10, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58787)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:51:21,301 DEBUG core.py Auth message = {'response': 511, 'bin': '8724d22a21adcef1d9f0978a9f5fc339252d5a5fa3739a2b92f54de0e3ee8fdf55879972ce1efaa760f7e9a7a1770673e1c4ff559fbd4778a058c7483370fbd6'}
2023-12-26 22:51:21,301 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=10, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58787)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:51:21,808 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=10, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58787)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:51:21,809 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703620281.302402, 'account_name': 'qwer'}
2023-12-26 22:51:21,809 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=10, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58787)>, {'response': 202, 'data_list': ['qwer', 'rewq', 'new']}) , {}. Вызов из модуля core.utils
2023-12-26 22:51:22,311 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=10, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58787)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:51:22,311 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1703620281.816242, 'user': 'qwer'}
2023-12-26 22:51:22,315 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=10, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58787)>, {'response': 202, 'data_list': ['new']}) , {}. Вызов из модуля core.utils
2023-12-26 22:54:22,486 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 22:54:22,486 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 22:54:22,487 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 22:54:22,487 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 22:54:22,487 DEBUG server.py Аргументы успешно загружены.
2023-12-26 22:54:22,492 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 22:54:34,330 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 22:54:34,330 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 22:54:34,330 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 22:54:34,330 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 22:54:34,331 DEBUG server.py Аргументы успешно загружены.
2023-12-26 22:54:34,332 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 22:54:49,992 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 22:54:49,992 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 22:54:49,993 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 22:54:49,993 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 22:54:49,993 DEBUG server.py Аргументы успешно загружены.
2023-12-26 22:54:49,995 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 22:55:49,975 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-26 22:55:49,975 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-26 22:55:49,976 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-26 22:55:49,976 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-26 22:55:49,976 DEBUG server.py Аргументы успешно загружены.
2023-12-26 22:55:49,978 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-12-26 22:57:33,189 INFO core.py Установлено соедение с ПК ('127.0.0.1', 58994)
2023-12-26 22:57:33,691 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58994)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:57:33,692 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703620653.1981041, 'user': {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiFl1DMQlrlQWYzAj80XQ\nR7vvAFUNyVg7N2onD7ZTxeqDtPP81/PlIV1V2+v3r6FGjpqpjt0+HQwxwu3ElXbe\nbd67x2d5wMI7Q7QiTXFr5Mf/zmReAabEhM2NGby6xQQWVo5uWzVlgk5cryvX92VA\nbdll6BXG8NP1HopO1FH4DF3TacXVJZyAjGvAsrczMDdd7zM7YuIOrZfipPVhoZnK\nBQ0ZWwl/bJQHZDG3q92tojztFegxhg5308C7XXxuJJPQvDF+y7uzEvgjhsxjanW9\nU/c2YCEN6eM8GiIf2k7de6mI3WzcHKvUEu83FBw9mNsvS+qkcdmf0wOn5CssEyaH\n5wIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 22:57:33,692 DEBUG core.py Start auth process for {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiFl1DMQlrlQWYzAj80XQ\nR7vvAFUNyVg7N2onD7ZTxeqDtPP81/PlIV1V2+v3r6FGjpqpjt0+HQwxwu3ElXbe\nbd67x2d5wMI7Q7QiTXFr5Mf/zmReAabEhM2NGby6xQQWVo5uWzVlgk5cryvX92VA\nbdll6BXG8NP1HopO1FH4DF3TacXVJZyAjGvAsrczMDdd7zM7YuIOrZfipPVhoZnK\nBQ0ZWwl/bJQHZDG3q92tojztFegxhg5308C7XXxuJJPQvDF+y7uzEvgjhsxjanW9\nU/c2YCEN6eM8GiIf2k7de6mI3WzcHKvUEu83FBw9mNsvS+qkcdmf0wOn5CssEyaH\n5wIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 22:57:33,695 DEBUG core.py Correct username, starting passwd check.
2023-12-26 22:57:33,695 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58994)>, {'response': 511, 'bin': 'c77bee4679e8e243e6e5a7958df9f676d495b9fd284b6e4225ddf7dde10183f92a70b8b581976119e644282da08b9688d4da802557251ddd844e934e9f25c3fd'}) , {}. Вызов из модуля core.utils
2023-12-26 22:57:33,696 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58994)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:57:33,697 DEBUG core.py Auth message = {'response': 511, 'bin': 'c77bee4679e8e243e6e5a7958df9f676d495b9fd284b6e4225ddf7dde10183f92a70b8b581976119e644282da08b9688d4da802557251ddd844e934e9f25c3fd'}
2023-12-26 22:57:33,698 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58994)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:57:34,211 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58994)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:57:34,211 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703620653.6984708, 'account_name': 'new'}
2023-12-26 22:57:34,214 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58994)>, {'response': 202, 'data_list': ['new', 'a']}) , {}. Вызов из модуля core.utils
2023-12-26 22:57:34,716 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58994)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:57:34,717 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1703620654.222118, 'user': 'new'}
2023-12-26 22:57:34,725 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 58994)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2023-12-26 22:57:43,340 INFO core.py Установлено соедение с ПК ('127.0.0.1', 59010)
2023-12-26 22:57:43,842 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59010)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:57:43,843 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1703620663.349731, 'user': {'account_name': 'a', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz4egvKcGoWzen/gehZrP\ntEBXewK/ZxfGtWG4dCwgEWlpWcIoNokaGbgV2TSSQebz26Wea4Y2HWT1isLr15B4\nHBcFakr87URaUJydfXzEESJ1n37pwK0syCTjz2WSpict1QmV/p/rAQJ6yt0hU5ZF\nY0XhAxGtid1Zg/LZZA0QTc/6ROu8j9/Q7+jl24eZGn0XhDV5t4XjM3z+rqFAMgFc\npkaSTsT09QBfRpd2SrkDU5CPFuVJRFkt6NMtAWtO4zU9mo10rz9GkxNR5o57g3+N\nPVGsbg3euGzaZd40g08RKYho5uBMEDdO0r6da180rOhIwGuBzEVtST2I8fU9V9NY\nzwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-12-26 22:57:43,843 DEBUG core.py Start auth process for {'account_name': 'a', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz4egvKcGoWzen/gehZrP\ntEBXewK/ZxfGtWG4dCwgEWlpWcIoNokaGbgV2TSSQebz26Wea4Y2HWT1isLr15B4\nHBcFakr87URaUJydfXzEESJ1n37pwK0syCTjz2WSpict1QmV/p/rAQJ6yt0hU5ZF\nY0XhAxGtid1Zg/LZZA0QTc/6ROu8j9/Q7+jl24eZGn0XhDV5t4XjM3z+rqFAMgFc\npkaSTsT09QBfRpd2SrkDU5CPFuVJRFkt6NMtAWtO4zU9mo10rz9GkxNR5o57g3+N\nPVGsbg3euGzaZd40g08RKYho5uBMEDdO0r6da180rOhIwGuBzEVtST2I8fU9V9NY\nzwIDAQAB\n-----END PUBLIC KEY-----'}
2023-12-26 22:57:43,846 DEBUG core.py Correct username, starting passwd check.
2023-12-26 22:57:43,846 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59010)>, {'response': 511, 'bin': 'f7671e32a412bf6dcb262d1839eda4615e8508df9de7903198fd7c2d65799e542efd75fe0b0c31ac2d3b5ab37c7f71889020b25d121f7d203ec129c4b6bcef12'}) , {}. Вызов из модуля core.utils
2023-12-26 22:57:43,846 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59010)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:57:43,848 DEBUG core.py Auth message = {'response': 511, 'bin': 'f7671e32a412bf6dcb262d1839eda4615e8508df9de7903198fd7c2d65799e542efd75fe0b0c31ac2d3b5ab37c7f71889020b25d121f7d203ec129c4b6bcef12'}
2023-12-26 22:57:43,848 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59010)>, {'response': 200}) , {}. Вызов из модуля core.utils
2023-12-26 22:57:44,354 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59010)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:57:44,354 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1703620663.8485298, 'account_name': 'a'}
2023-12-26 22:57:44,356 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59010)>, {'response': 202, 'data_list': ['new', 'a']}) , {}. Вызов из модуля core.utils
2023-12-26 22:57:44,857 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59010)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:57:44,858 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1703620664.366064, 'user': 'a'}
2023-12-26 22:57:44,862 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59010)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2023-12-26 22:58:41,489 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59010)>,) , {}. Вызов из модуля core.utils
2023-12-26 22:58:41,490 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1703620721.4354491, 'account_name': 'a'}
2023-12-26 22:58:41,490 INFO core.py Клиент ('127.0.0.1', 59010) отключился от сервера.
2023-12-27 20:35:37,127 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-27 20:35:37,128 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-27 20:35:37,129 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-27 20:35:37,129 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/messeghost8740/server.py']
2023-12-27 20:35:37,130 DEBUG server.py Аргументы успешно загружены.
2023-12-27 20:35:49,104 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-27 20:35:49,104 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-27 20:35:49,104 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-27 20:35:49,104 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/server/messeghost8740/server.py']
2023-12-27 20:35:49,105 DEBUG server.py Аргументы успешно загружены.
2023-12-27 20:36:33,632 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-12-27 20:36:33,632 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2023-12-27 20:36:33,633 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-12-27 20:36:33,633 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2023-12-27 20:36:33,633 DEBUG server.py Аргументы успешно загружены.
2023-12-27 20:36:33,635 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
