2024-01-11 18:50:14.782 | DEBUG    | aria2p.interface:run:520 - Created new screen <tests.test_interface.MockedScreen object at 0x7f5c8ec35400>
2024-01-11 18:50:14.783 | DEBUG    | aria2p.interface:run:535 - Got event None
2024-01-11 18:50:14.783 | DEBUG    | aria2p.interface:run:551 - Tick! Updating data and rows
2024-01-11 18:50:14.804 | DEBUG    | aria2p.interface:run:558 - Refresh! Printing text
2024-01-11 18:50:14.810 | DEBUG    | aria2p.interface:run:535 - Got event KeyboardEvent: -102
2024-01-11 18:50:14.811 | DEBUG    | aria2p.interface:process_keyboard_event_main:691 - Triggered removal
2024-01-11 18:50:14.811 | DEBUG    | aria2p.interface:process_keyboard_event_main:692 - self.focused = 0
2024-01-11 18:50:14.811 | DEBUG    | aria2p.interface:process_keyboard_event_main:693 - len(self.data) = 2
2024-01-11 18:50:14.811 | DEBUG    | aria2p.interface:run:547 - Got event KeyboardEvent: -206
2024-01-11 18:50:14.811 | DEBUG    | aria2p.interface:process_keyboard_event_remove_ask:852 - Moving side focus down: 1
2024-01-11 18:50:14.811 | DEBUG    | aria2p.interface:run:547 - Got event KeyboardEvent: 10
2024-01-11 18:50:14.811 | DEBUG    | aria2p.interface:process_keyboard_event_remove_ask:830 - Validate removal
2024-01-11 18:50:14.812 | DEBUG    | aria2p.api:remove:435 - Try to remove download 0000000000000001
2024-01-11 18:50:14.815 | SUCCESS  | aria2p.api:remove:442 - Removed download 0000000000000001
2024-01-11 18:50:14.818 | DEBUG    | aria2p.api:remove:447 - Failed to remove download result 0000000000000001
2024-01-11 18:50:14.818 | TRACE    | aria2p.api:remove:448 - GID 0000000000000001 is not found
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 1640, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw0-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f5c95f06630>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 1142, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f5c95f79620>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f5c968f73b0>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f5c95f959a0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 343, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f5c95f47a40>
    │    └ <function WorkerPool._perform_spawn at 0x7f5c95f79800>
    └ <execnet.gateway_base.WorkerPool object at 0x7f5c968f73b0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 361, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f5c95f794e0>
    └ <execnet.gateway_base.Reply object at 0x7f5c95f47a40>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 296, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f5c95f959a0>>
    └ <execnet.gateway_base.Reply object at 0x7f5c95f47a40>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 1157, in executetask
    exec(co, loc)
         │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
         └ <code object <module> at 0x55605ccb5a80, file "/media/data/dev/aria2p/__pypackages__/3.12/lib/xdist/remote.py", line 1>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/xdist/remote.py", line 355, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f5c951842c0>
    │      │    └ <HookCaller 'pytest_cmdline_main'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f5c952c1a30>
    └ <_pytest.config.Config object at 0x7f5c951842c0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'config': <_pytest.config.Config object at 0x7f5c951842c0>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_cmdline_main'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_cmdline_main'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f5c951842c0>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f5c968b1760>
           └ <_pytest.config.PytestPluginManager object at 0x7f5c95676810>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f5c951842c0>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/main.py", line 318, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f5c9523d620>
           │            └ <_pytest.config.Config object at 0x7f5c951842c0>
           └ <function wrap_session at 0x7f5c9523d580>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/main.py", line 271, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>
    │       │            │    └ <_pytest.config.Config object at 0x7f5c951842c0>
    │       │            └ <function _main at 0x7f5c9523d620>
    │       └ <ExitCode.OK: 0>
    └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/main.py", line 325, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>
    │      │    └ <HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f5c952c1a30>
    └ <_pytest.config.Config object at 0x7f5c951842c0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtestloop'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtestloop'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f5c968b1760>
           └ <_pytest.config.PytestPluginManager object at 0x7f5c95676810>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='140035599025936', plugin=<__channelexec__.WorkerInteractor object at 0x7f5c9422c710>>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/xdist/remote.py", line 157, in pytest_runtestloop
    self.run_one_test()
    │    └ <function WorkerInteractor.run_one_test at 0x7f5c94fd8040>
    └ <__channelexec__.WorkerInteractor object at 0x7f5c9422c710>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/xdist/remote.py", line 174, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_change_sort>
    │    │      │    │                            └ <Function test_remember_last_remove>
    │    │      │    └ <HookCaller 'pytest_runtest_protocol'>
    │    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f5c952c1a30>
    │    └ <_pytest.config.Config object at 0x7f5c951842c0>
    └ <__channelexec__.WorkerInteractor object at 0x7f5c9422c710>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'item': <Function test_remember_last_remove>, 'nextitem': <Function test_change_sort>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_protocol'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remember_last_remove>, 'nextitem': <Function test_change_sort>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f5c968b1760>
           └ <_pytest.config.PytestPluginManager object at 0x7f5c95676810>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remember_last_remove>, <Function test_change_sort>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.12...
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pytest_rerunfailures.py", line 541, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_change_sort>
              │               └ <Function test_remember_last_remove>
              └ <function runtestprotocol at 0x7f5c9523c7c0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 133, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remember_last_remove>
    │       │      └ <function call_and_report at 0x7f5c9523cb80>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_interface.py::test_remember_last_remove' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 222, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remember_last_remove>
           └ <function call_runtest_hook at 0x7f5c9523cd60>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 261, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f5c9523cfe0>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f5c8ecc0540>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remember_last_remove>
            └ <HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ False
           │    │         │    │     │    │           └ {'item': <Function test_remember_last_remove>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remember_last_remove>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f5c968b1760>
           └ <_pytest.config.PytestPluginManager object at 0x7f5c95676810>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remember_last_remove>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f5c95287880>
    └ <Function test_remember_last_remove>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remember_last_remove>
    │    └ <property object at 0x7f5c9539a430>
    └ <Function test_remember_last_remove>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'pyfuncitem': <Function test_remember_last_remove>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_pyfunc_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remember_last_remove>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f5c968b1760>
           └ <_pytest.config.PytestPluginManager object at 0x7f5c95676810>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remember_last_remove>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-32/popen-gw0/test_remember_last_remove0'), 'port': 15139, 'monkeypatch'...
             └ <function test_remember_last_remove at 0x7f5c8fb3d080>

  File "/media/data/dev/aria2p/tests/test_interface.py", line 386, in test_remember_last_remove
    interface = run_interface(
                └ <function run_interface at 0x7f5c8fadff60>

  File "/media/data/dev/aria2p/tests/test_interface.py", line 124, in run_interface
    interface.run()
    │         └ <function Interface.run at 0x7f5c8fe55580>
    └ <aria2p.interface.Interface object at 0x7f5c940d1d30>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 539, in run
    self.process_event(event)
    │    │             └ KeyboardEvent: 10
    │    └ <function Interface.process_event at 0x7f5c8fe556c0>
    └ <aria2p.interface.Interface object at 0x7f5c940d1d30>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 602, in process_event
    self.process_keyboard_event(event)
    │    │                      └ KeyboardEvent: 10
    │    └ <function Interface.process_keyboard_event at 0x7f5c8fe55760>
    └ <aria2p.interface.Interface object at 0x7f5c940d1d30>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 608, in process_keyboard_event
    self.state_mapping[self.state]["process_keyboard_event"](event)
    │    │             │    │                                └ KeyboardEvent: 10
    │    │             │    └ 3
    │    │             └ <aria2p.interface.Interface object at 0x7f5c940d1d30>
    │    └ {0: {'process_keyboard_event': <bound method Interface.process_keyboard_event_main of <aria2p.interface.Interface object at 0...
    └ <aria2p.interface.Interface object at 0x7f5c940d1d30>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 832, in process_keyboard_event_remove_ask
    self.remove_ask_rows[self.side_focused][1](self.follow)
    │    │               │    │                │    └ <aria2p.downloads.Download object at 0x7f5c8ec35790>
    │    │               │    │                └ <aria2p.interface.Interface object at 0x7f5c940d1d30>
    │    │               │    └ 1
    │    │               └ <aria2p.interface.Interface object at 0x7f5c940d1d30>
    │    └ [('Remove', <function Interface.<lambda> at 0x7f5c8fe551c0>), ('Remove with files', <function Interface.<lambda> at 0x7f5c8fe...
    └ <aria2p.interface.Interface object at 0x7f5c940d1d30>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 442, in <lambda>
    ("Remove with files", lambda d: d.remove(force=False, files=True)),
                                 │  │ └ <function Download.remove at 0x7f5c94258680>
                                 │  └ <aria2p.downloads.Download object at 0x7f5c8ec35790>
                                 └ <aria2p.downloads.Download object at 0x7f5c8ec35790>

  File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 956, in remove
    result = self.api.remove([self], force=force, files=files)[0]
             │    │   │       │            │            └ True
             │    │   │       │            └ False
             │    │   │       └ <aria2p.downloads.Download object at 0x7f5c8ec35790>
             │    │   └ <function API.remove at 0x7f5c940b8fe0>
             │    └ API(Client(host='http://localhost', port=15139, secret='********'))
             └ <aria2p.downloads.Download object at 0x7f5c8ec35790>

> File "/media/data/dev/aria2p/src/aria2p/api.py", line 445, in remove
    self.client.remove_download_result(download.gid)
    │    │      │                      │        └ <property object at 0x7f5c9422bdd0>
    │    │      │                      └ <aria2p.downloads.Download object at 0x7f5c8ec35790>
    │    │      └ <function Client.remove_download_result at 0x7f5c94238040>
    │    └ Client(host='http://localhost', port=15139, secret='********')
    └ API(Client(host='http://localhost', port=15139, secret='********'))

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 1418, in remove_download_result
    return self.call(self.REMOVE_DOWNLOAD_RESULT, [gid])  # type: ignore
           │    │    │    │                        └ '0000000000000001'
           │    │    │    └ 'aria2.removeDownloadResult'
           │    │    └ Client(host='http://localhost', port=15139, secret='********')
           │    └ <function Client.call at 0x7f5c94226a20>
           └ Client(host='http://localhost', port=15139, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 258, in call
    return self.res_or_raise(self.post(payload))
           │    │            │    │    └ '{"jsonrpc": "2.0", "method": "aria2.removeDownloadResult", "id": -1, "params": ["0000000000000001"]}'
           │    │            │    └ <function Client.post at 0x7f5c94226c00>
           │    │            └ Client(host='http://localhost', port=15139, secret='********')
           │    └ <staticmethod(<function Client.res_or_raise at 0x7f5c94226d40>)>
           └ Client(host='http://localhost', port=15139, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 380, in res_or_raise
    raise Client.response_as_exception(response)
          │      │                     └ {'id': -1, 'jsonrpc': '2.0', 'error': {'code': 1, 'message': 'GID 0000000000000001 is not found'}}
          │      └ <staticmethod(<function Client.response_as_exception at 0x7f5c94226ca0>)>
          └ <class 'aria2p.client.Client'>

aria2p.client.ClientException: GID 0000000000000001 is not found
2024-01-11 18:50:14.829 | DEBUG    | aria2p.api:remove:461 - Removed control file /tmp/pytest-of-pawamoy/pytest-32/popen-gw0/test_remember_last_remove0/5m.aria2
2024-01-11 18:50:14.830 | WARNING  | aria2p.downloads:root_files_paths:330 - Can't determine file path '.' relative to '/tmp/pytest-of-pawamoy/pytest-32/popen-gw0/test_remember_last_remove0'
2024-01-11 18:50:14.832 | TRACE    | aria2p.downloads:root_files_paths:331 - '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-32/popen-gw0/test_remember_last_remove0'
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 1640, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw0-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f5c95f06630>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 1142, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f5c95f79620>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f5c968f73b0>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f5c95f959a0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 343, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f5c95f47a40>
    │    └ <function WorkerPool._perform_spawn at 0x7f5c95f79800>
    └ <execnet.gateway_base.WorkerPool object at 0x7f5c968f73b0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 361, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f5c95f794e0>
    └ <execnet.gateway_base.Reply object at 0x7f5c95f47a40>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 296, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f5c95f959a0>>
    └ <execnet.gateway_base.Reply object at 0x7f5c95f47a40>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/execnet/gateway_base.py", line 1157, in executetask
    exec(co, loc)
         │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
         └ <code object <module> at 0x55605ccb5a80, file "/media/data/dev/aria2p/__pypackages__/3.12/lib/xdist/remote.py", line 1>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/xdist/remote.py", line 355, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f5c951842c0>
    │      │    └ <HookCaller 'pytest_cmdline_main'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f5c952c1a30>
    └ <_pytest.config.Config object at 0x7f5c951842c0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'config': <_pytest.config.Config object at 0x7f5c951842c0>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_cmdline_main'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_cmdline_main'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f5c951842c0>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f5c968b1760>
           └ <_pytest.config.PytestPluginManager object at 0x7f5c95676810>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f5c951842c0>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/main.py", line 318, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f5c9523d620>
           │            └ <_pytest.config.Config object at 0x7f5c951842c0>
           └ <function wrap_session at 0x7f5c9523d580>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/main.py", line 271, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>
    │       │            │    └ <_pytest.config.Config object at 0x7f5c951842c0>
    │       │            └ <function _main at 0x7f5c9523d620>
    │       └ <ExitCode.OK: 0>
    └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/main.py", line 325, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>
    │      │    └ <HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f5c952c1a30>
    └ <_pytest.config.Config object at 0x7f5c951842c0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtestloop'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtestloop'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f5c968b1760>
           └ <_pytest.config.PytestPluginManager object at 0x7f5c95676810>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=485>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='140035599025936', plugin=<__channelexec__.WorkerInteractor object at 0x7f5c9422c710>>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/xdist/remote.py", line 157, in pytest_runtestloop
    self.run_one_test()
    │    └ <function WorkerInteractor.run_one_test at 0x7f5c94fd8040>
    └ <__channelexec__.WorkerInteractor object at 0x7f5c9422c710>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/xdist/remote.py", line 174, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_change_sort>
    │    │      │    │                            └ <Function test_remember_last_remove>
    │    │      │    └ <HookCaller 'pytest_runtest_protocol'>
    │    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f5c952c1a30>
    │    └ <_pytest.config.Config object at 0x7f5c951842c0>
    └ <__channelexec__.WorkerInteractor object at 0x7f5c9422c710>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'item': <Function test_remember_last_remove>, 'nextitem': <Function test_change_sort>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_protocol'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remember_last_remove>, 'nextitem': <Function test_change_sort>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f5c968b1760>
           └ <_pytest.config.PytestPluginManager object at 0x7f5c95676810>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remember_last_remove>, <Function test_change_sort>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.12...
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pytest_rerunfailures.py", line 541, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_change_sort>
              │               └ <Function test_remember_last_remove>
              └ <function runtestprotocol at 0x7f5c9523c7c0>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 133, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remember_last_remove>
    │       │      └ <function call_and_report at 0x7f5c9523cb80>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_interface.py::test_remember_last_remove' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 222, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remember_last_remove>
           └ <function call_runtest_hook at 0x7f5c9523cd60>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 261, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f5c9523cfe0>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f5c8ecc0540>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remember_last_remove>
            └ <HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ False
           │    │         │    │     │    │           └ {'item': <Function test_remember_last_remove>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remember_last_remove>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f5c968b1760>
           └ <_pytest.config.PytestPluginManager object at 0x7f5c95676810>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remember_last_remove>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f5c95287880>
    └ <Function test_remember_last_remove>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remember_last_remove>
    │    └ <property object at 0x7f5c9539a430>
    └ <Function test_remember_last_remove>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'pyfuncitem': <Function test_remember_last_remove>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_pyfunc_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remember_last_remove>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f5c968b1760>
           └ <_pytest.config.PytestPluginManager object at 0x7f5c95676810>
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remember_last_remove>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.12/lib/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-32/popen-gw0/test_remember_last_remove0'), 'port': 15139, 'monkeypatch'...
             └ <function test_remember_last_remove at 0x7f5c8fb3d080>

  File "/media/data/dev/aria2p/tests/test_interface.py", line 386, in test_remember_last_remove
    interface = run_interface(
                └ <function run_interface at 0x7f5c8fadff60>

  File "/media/data/dev/aria2p/tests/test_interface.py", line 124, in run_interface
    interface.run()
    │         └ <function Interface.run at 0x7f5c8fe55580>
    └ <aria2p.interface.Interface object at 0x7f5c940d1d30>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 539, in run
    self.process_event(event)
    │    │             └ KeyboardEvent: 10
    │    └ <function Interface.process_event at 0x7f5c8fe556c0>
    └ <aria2p.interface.Interface object at 0x7f5c940d1d30>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 602, in process_event
    self.process_keyboard_event(event)
    │    │                      └ KeyboardEvent: 10
    │    └ <function Interface.process_keyboard_event at 0x7f5c8fe55760>
    └ <aria2p.interface.Interface object at 0x7f5c940d1d30>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 608, in process_keyboard_event
    self.state_mapping[self.state]["process_keyboard_event"](event)
    │    │             │    │                                └ KeyboardEvent: 10
    │    │             │    └ 3
    │    │             └ <aria2p.interface.Interface object at 0x7f5c940d1d30>
    │    └ {0: {'process_keyboard_event': <bound method Interface.process_keyboard_event_main of <aria2p.interface.Interface object at 0...
    └ <aria2p.interface.Interface object at 0x7f5c940d1d30>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 832, in process_keyboard_event_remove_ask
    self.remove_ask_rows[self.side_focused][1](self.follow)
    │    │               │    │                │    └ <aria2p.downloads.Download object at 0x7f5c8ec35790>
    │    │               │    │                └ <aria2p.interface.Interface object at 0x7f5c940d1d30>
    │    │               │    └ 1
    │    │               └ <aria2p.interface.Interface object at 0x7f5c940d1d30>
    │    └ [('Remove', <function Interface.<lambda> at 0x7f5c8fe551c0>), ('Remove with files', <function Interface.<lambda> at 0x7f5c8fe...
    └ <aria2p.interface.Interface object at 0x7f5c940d1d30>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 442, in <lambda>
    ("Remove with files", lambda d: d.remove(force=False, files=True)),
                                 │  │ └ <function Download.remove at 0x7f5c94258680>
                                 │  └ <aria2p.downloads.Download object at 0x7f5c8ec35790>
                                 └ <aria2p.downloads.Download object at 0x7f5c8ec35790>

  File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 956, in remove
    result = self.api.remove([self], force=force, files=files)[0]
             │    │   │       │            │            └ True
             │    │   │       │            └ False
             │    │   │       └ <aria2p.downloads.Download object at 0x7f5c8ec35790>
             │    │   └ <function API.remove at 0x7f5c940b8fe0>
             │    └ API(Client(host='http://localhost', port=15139, secret='********'))
             └ <aria2p.downloads.Download object at 0x7f5c8ec35790>

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 464, in remove
    self.remove_files([download], force=True)
    │    │             └ <aria2p.downloads.Download object at 0x7f5c8ec35790>
    │    └ <staticmethod(<function API.remove_files at 0x7f5c940b9800>)>
    └ API(Client(host='http://localhost', port=15139, secret='********'))

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 650, in remove_files
    for path in download.root_files_paths:
                │        └ <property object at 0x7f5c9422bd80>
                └ <aria2p.downloads.Download object at 0x7f5c8ec35790>

> File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 328, in root_files_paths
    relative_path = file.path.relative_to(self.dir)
                    │    │                │    └ <property object at 0x7f5c94248810>
                    │    │                └ <aria2p.downloads.Download object at 0x7f5c8ec35790>
                    │    └ <property object at 0x7f5c9422b420>
                    └ <aria2p.downloads.File object at 0x7f5c8ec35160>

  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.12.0/lib/python3.12/pathlib.py", line 683, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
                            │                                      └ PosixPath('/tmp/pytest-of-pawamoy/pytest-32/popen-gw0/test_remember_last_remove0')
                            └ PosixPath('.')

ValueError: '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-32/popen-gw0/test_remember_last_remove0'
2024-01-11 18:50:14.845 | DEBUG    | aria2p.interface:run:547 - Got event KeyboardEvent: -102
2024-01-11 18:50:14.845 | DEBUG    | aria2p.interface:process_keyboard_event_main:691 - Triggered removal
2024-01-11 18:50:14.845 | DEBUG    | aria2p.interface:process_keyboard_event_main:692 - self.focused = 0
2024-01-11 18:50:14.846 | DEBUG    | aria2p.interface:process_keyboard_event_main:693 - len(self.data) = 2
2024-01-11 18:50:14.846 | DEBUG    | aria2p.interface:run:547 - Got event KeyboardEvent: -1
2024-01-11 18:50:14.846 | DEBUG    | aria2p.interface:process_keyboard_event_remove_ask:824 - Canceling removal
2024-01-11 18:50:14.846 | DEBUG    | aria2p.interface:run:547 - Got event KeyboardEvent: 113
2024-01-11 18:50:14.846 | DEBUG    | aria2p.interface:run:541 - Received exit command
