2024-01-08 18:52:34,187 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 18:52:34,187 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 18:52:34,188 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 18:52:34,188 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2024-01-08 18:52:34,188 DEBUG server.py Аргументы успешно загружены.
2024-01-08 18:52:34,190 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2024-01-08 18:53:25,009 INFO core.py Установлено соедение с ПК ('127.0.0.1', 50719)
2024-01-08 18:53:25,511 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50719)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:53:25,512 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1704729205.019843, 'user': {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo/1xZf3Skm01y9+ZY5zx\n2aqkyD1Fr1sCTTJtHin1vPJWIIihl+uipr2bncPGFoFpOuhrEiOEiYMyvTYPAHcA\nFfiH90IAYLQ5zRTFcVxKYFjb2uMelJXqXMfOiURm5u48K7wXdaZcuvm4rNrDp2v5\npPsl/pwKVdhH5km/b2wYwZ3L6W2HadXBB/te0eackHlkN0/aNuRc78Bx3rOh9e46\n2vKPxt0hPbZ/914VRD4Dd/xcRF6R5PW/WCtRgjMLo5GQd7HmB4N8ViEKSxPCovTE\nnWJo+PZhaKZukdqnNjlllfiARuKvcmiBIPUMWoktDDOoaC1JOzBS7c/vfFz1BiKm\ntQIDAQAB\n-----END PUBLIC KEY-----'}}
2024-01-08 18:53:25,512 DEBUG core.py Start auth process for {'account_name': 'new', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo/1xZf3Skm01y9+ZY5zx\n2aqkyD1Fr1sCTTJtHin1vPJWIIihl+uipr2bncPGFoFpOuhrEiOEiYMyvTYPAHcA\nFfiH90IAYLQ5zRTFcVxKYFjb2uMelJXqXMfOiURm5u48K7wXdaZcuvm4rNrDp2v5\npPsl/pwKVdhH5km/b2wYwZ3L6W2HadXBB/te0eackHlkN0/aNuRc78Bx3rOh9e46\n2vKPxt0hPbZ/914VRD4Dd/xcRF6R5PW/WCtRgjMLo5GQd7HmB4N8ViEKSxPCovTE\nnWJo+PZhaKZukdqnNjlllfiARuKvcmiBIPUMWoktDDOoaC1JOzBS7c/vfFz1BiKm\ntQIDAQAB\n-----END PUBLIC KEY-----'}
2024-01-08 18:53:25,520 DEBUG core.py Correct username, starting passwd check.
2024-01-08 18:53:25,520 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50719)>, {'response': 511, 'bin': 'e3a7e24d6d89aef11983584ad5be122754b001f9f05f5a91fd96df746d44b72e7904ae35cb17ec84d058fbbc27a07cf3f472eaf09f7952c8c865de1c7d11252d'}) , {}. Вызов из модуля core.utils
2024-01-08 18:53:25,520 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50719)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:53:25,521 DEBUG core.py Auth message = {'response': 511, 'bin': 'e3a7e24d6d89aef11983584ad5be122754b001f9f05f5a91fd96df746d44b72e7904ae35cb17ec84d058fbbc27a07cf3f472eaf09f7952c8c865de1c7d11252d'}
2024-01-08 18:53:25,521 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50719)>, {'response': 200}) , {}. Вызов из модуля core.utils
2024-01-08 18:54:53,297 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 18:54:53,297 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 18:54:53,297 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 18:54:53,297 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2024-01-08 18:54:53,298 DEBUG server.py Аргументы успешно загружены.
2024-01-08 18:54:53,303 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2024-01-08 18:55:26,474 INFO core.py Установлено соедение с ПК ('127.0.0.1', 50733)
2024-01-08 18:55:26,976 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:55:26,977 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1704729326.483386, 'user': {'account_name': 'one', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyJamJnF6vbKpZY84HAgc\nlOgxj8bx2d8N9ITHwvJ2Cx5LDsaqGbanovcyP5Oo9VEIJgf53QWkYSTf2HxDBdPG\nxrhbzr7ho5yteGLTqsTpM/C0bVLsC8x5+MkT+Hv+H8Rw32o4RYiwCCvTOzkbODkn\nfCfebpFJcg16mo+TDctFOQ880qAZmAv8rfud36Za1Z7SefZyFcvD6bnxEN7yfpST\nr4IawraKkSqvm5XirEhmN/iEn/JBvHIWsCK9WpezsT9n+Dy1KNp9KNOXvgX77c9+\nFQ6j2ZHpA0TkWYG+N+wL9bbgGYlEtVrzZYRWcRoUPKuTstIXfFH7hkTYcbuuMyqu\nLwIDAQAB\n-----END PUBLIC KEY-----'}}
2024-01-08 18:55:26,977 DEBUG core.py Start auth process for {'account_name': 'one', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyJamJnF6vbKpZY84HAgc\nlOgxj8bx2d8N9ITHwvJ2Cx5LDsaqGbanovcyP5Oo9VEIJgf53QWkYSTf2HxDBdPG\nxrhbzr7ho5yteGLTqsTpM/C0bVLsC8x5+MkT+Hv+H8Rw32o4RYiwCCvTOzkbODkn\nfCfebpFJcg16mo+TDctFOQ880qAZmAv8rfud36Za1Z7SefZyFcvD6bnxEN7yfpST\nr4IawraKkSqvm5XirEhmN/iEn/JBvHIWsCK9WpezsT9n+Dy1KNp9KNOXvgX77c9+\nFQ6j2ZHpA0TkWYG+N+wL9bbgGYlEtVrzZYRWcRoUPKuTstIXfFH7hkTYcbuuMyqu\nLwIDAQAB\n-----END PUBLIC KEY-----'}
2024-01-08 18:55:26,980 DEBUG core.py Correct username, starting passwd check.
2024-01-08 18:55:26,981 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 511, 'bin': '0095a158776e36223b7ba0932d2f15aa6ae6eb0e45c0b4b82cb0049c537360eb4e4668251b9e98cd76e66d42db9ebe4e44040e9a81229136f3503a3514b8b680'}) , {}. Вызов из модуля core.utils
2024-01-08 18:55:26,981 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:55:26,983 DEBUG core.py Auth message = {'response': 511, 'bin': '0095a158776e36223b7ba0932d2f15aa6ae6eb0e45c0b4b82cb0049c537360eb4e4668251b9e98cd76e66d42db9ebe4e44040e9a81229136f3503a3514b8b680'}
2024-01-08 18:55:26,983 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 200}) , {}. Вызов из модуля core.utils
2024-01-08 18:55:27,493 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:55:27,493 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1704729326.984462, 'account_name': 'one'}
2024-01-08 18:55:27,495 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 202, 'data_list': ['one', 'two']}) , {}. Вызов из модуля core.utils
2024-01-08 18:55:27,996 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:55:27,997 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1704729327.50355, 'user': 'one'}
2024-01-08 18:55:28,003 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2024-01-08 18:55:56,608 INFO core.py Установлено соедение с ПК ('127.0.0.1', 50738)
2024-01-08 18:55:57,109 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50738)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:55:57,110 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1704729356.617186, 'user': {'account_name': 'two', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArC0Y2Ag0NY64QTpSe14D\nVa17GtdYoN8zYGrsmHY3QhWHKdHwWpDzVYKW6ZpSLALwdGGL9FfogQ0Q/rBG/CUl\nFrT619HaTTkWn+jPw+uxrbh9PS1pRHlCydjNydtEo71Sr/LVv3xIznMuRobj7RPO\nPoT4d64UJ0n3BrPpzC7UUXcXFzL6V8FmCm5Waqj/3XQR+UBMs4PsMgjOiJllc3q7\nrsifd0KxtFOizYvvIP3U8/XuLriKLjhiJGXx8GAXiBS5jVHBDaRLrbJUtAeFV4nX\nDbVXXHWKIyTpjEEdia/bTcHamyWYqo36r0ES+U83LH4ENMPfh1XBW0ncmIm96XMd\n4wIDAQAB\n-----END PUBLIC KEY-----'}}
2024-01-08 18:55:57,110 DEBUG core.py Start auth process for {'account_name': 'two', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArC0Y2Ag0NY64QTpSe14D\nVa17GtdYoN8zYGrsmHY3QhWHKdHwWpDzVYKW6ZpSLALwdGGL9FfogQ0Q/rBG/CUl\nFrT619HaTTkWn+jPw+uxrbh9PS1pRHlCydjNydtEo71Sr/LVv3xIznMuRobj7RPO\nPoT4d64UJ0n3BrPpzC7UUXcXFzL6V8FmCm5Waqj/3XQR+UBMs4PsMgjOiJllc3q7\nrsifd0KxtFOizYvvIP3U8/XuLriKLjhiJGXx8GAXiBS5jVHBDaRLrbJUtAeFV4nX\nDbVXXHWKIyTpjEEdia/bTcHamyWYqo36r0ES+U83LH4ENMPfh1XBW0ncmIm96XMd\n4wIDAQAB\n-----END PUBLIC KEY-----'}
2024-01-08 18:55:57,114 DEBUG core.py Correct username, starting passwd check.
2024-01-08 18:55:57,114 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50738)>, {'response': 511, 'bin': 'bb78fd137d3879c82a5abe7f3d11e3915e44000a176c00526b279d3ef6352a40a5acd5d56589d7667717e19baeb24ae3c721905c42efe92f7630b45d7042b077'}) , {}. Вызов из модуля core.utils
2024-01-08 18:55:57,115 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50738)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:55:57,116 DEBUG core.py Auth message = {'response': 511, 'bin': 'bb78fd137d3879c82a5abe7f3d11e3915e44000a176c00526b279d3ef6352a40a5acd5d56589d7667717e19baeb24ae3c721905c42efe92f7630b45d7042b077'}
2024-01-08 18:55:57,116 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50738)>, {'response': 400, 'error': 'Неверный пароль.'}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:04,381 INFO core.py Установлено соедение с ПК ('127.0.0.1', 50739)
2024-01-08 18:56:04,883 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50739)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:04,884 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1704729364.3907928, 'user': {'account_name': 'two', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArC0Y2Ag0NY64QTpSe14D\nVa17GtdYoN8zYGrsmHY3QhWHKdHwWpDzVYKW6ZpSLALwdGGL9FfogQ0Q/rBG/CUl\nFrT619HaTTkWn+jPw+uxrbh9PS1pRHlCydjNydtEo71Sr/LVv3xIznMuRobj7RPO\nPoT4d64UJ0n3BrPpzC7UUXcXFzL6V8FmCm5Waqj/3XQR+UBMs4PsMgjOiJllc3q7\nrsifd0KxtFOizYvvIP3U8/XuLriKLjhiJGXx8GAXiBS5jVHBDaRLrbJUtAeFV4nX\nDbVXXHWKIyTpjEEdia/bTcHamyWYqo36r0ES+U83LH4ENMPfh1XBW0ncmIm96XMd\n4wIDAQAB\n-----END PUBLIC KEY-----'}}
2024-01-08 18:56:04,884 DEBUG core.py Start auth process for {'account_name': 'two', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArC0Y2Ag0NY64QTpSe14D\nVa17GtdYoN8zYGrsmHY3QhWHKdHwWpDzVYKW6ZpSLALwdGGL9FfogQ0Q/rBG/CUl\nFrT619HaTTkWn+jPw+uxrbh9PS1pRHlCydjNydtEo71Sr/LVv3xIznMuRobj7RPO\nPoT4d64UJ0n3BrPpzC7UUXcXFzL6V8FmCm5Waqj/3XQR+UBMs4PsMgjOiJllc3q7\nrsifd0KxtFOizYvvIP3U8/XuLriKLjhiJGXx8GAXiBS5jVHBDaRLrbJUtAeFV4nX\nDbVXXHWKIyTpjEEdia/bTcHamyWYqo36r0ES+U83LH4ENMPfh1XBW0ncmIm96XMd\n4wIDAQAB\n-----END PUBLIC KEY-----'}
2024-01-08 18:56:04,887 DEBUG core.py Correct username, starting passwd check.
2024-01-08 18:56:04,887 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50739)>, {'response': 511, 'bin': '3ed69b0c28e5f20dbfbbb3a1cbdbda6b91db0777234f39ce265e6e9b78226e497b2b6c814bc3a794a602d9337b06f51db324eba4facc8e53893dea648baba950'}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:04,887 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50739)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:04,889 DEBUG core.py Auth message = {'response': 511, 'bin': '3ed69b0c28e5f20dbfbbb3a1cbdbda6b91db0777234f39ce265e6e9b78226e497b2b6c814bc3a794a602d9337b06f51db324eba4facc8e53893dea648baba950'}
2024-01-08 18:56:04,889 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50739)>, {'response': 400, 'error': 'Неверный пароль.'}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:17,716 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 205}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:18,919 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:18,920 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1704729378.7137642, 'account_name': 'one'}
2024-01-08 18:56:18,921 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 202, 'data_list': ['one']}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:19,423 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:19,423 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1704729378.9311202, 'user': 'one'}
2024-01-08 18:56:19,425 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:31,769 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 205}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:32,958 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:32,958 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1704729392.4767842, 'account_name': 'one'}
2024-01-08 18:56:32,960 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 202, 'data_list': ['one', 'two']}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:33,462 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:33,462 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1704729392.969503, 'user': 'one'}
2024-01-08 18:56:33,464 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:37,971 INFO core.py Установлено соедение с ПК ('127.0.0.1', 50743)
2024-01-08 18:56:38,472 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:38,473 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1704729397.980261, 'user': {'account_name': 'two', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArC0Y2Ag0NY64QTpSe14D\nVa17GtdYoN8zYGrsmHY3QhWHKdHwWpDzVYKW6ZpSLALwdGGL9FfogQ0Q/rBG/CUl\nFrT619HaTTkWn+jPw+uxrbh9PS1pRHlCydjNydtEo71Sr/LVv3xIznMuRobj7RPO\nPoT4d64UJ0n3BrPpzC7UUXcXFzL6V8FmCm5Waqj/3XQR+UBMs4PsMgjOiJllc3q7\nrsifd0KxtFOizYvvIP3U8/XuLriKLjhiJGXx8GAXiBS5jVHBDaRLrbJUtAeFV4nX\nDbVXXHWKIyTpjEEdia/bTcHamyWYqo36r0ES+U83LH4ENMPfh1XBW0ncmIm96XMd\n4wIDAQAB\n-----END PUBLIC KEY-----'}}
2024-01-08 18:56:38,473 DEBUG core.py Start auth process for {'account_name': 'two', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArC0Y2Ag0NY64QTpSe14D\nVa17GtdYoN8zYGrsmHY3QhWHKdHwWpDzVYKW6ZpSLALwdGGL9FfogQ0Q/rBG/CUl\nFrT619HaTTkWn+jPw+uxrbh9PS1pRHlCydjNydtEo71Sr/LVv3xIznMuRobj7RPO\nPoT4d64UJ0n3BrPpzC7UUXcXFzL6V8FmCm5Waqj/3XQR+UBMs4PsMgjOiJllc3q7\nrsifd0KxtFOizYvvIP3U8/XuLriKLjhiJGXx8GAXiBS5jVHBDaRLrbJUtAeFV4nX\nDbVXXHWKIyTpjEEdia/bTcHamyWYqo36r0ES+U83LH4ENMPfh1XBW0ncmIm96XMd\n4wIDAQAB\n-----END PUBLIC KEY-----'}
2024-01-08 18:56:38,476 DEBUG core.py Correct username, starting passwd check.
2024-01-08 18:56:38,477 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>, {'response': 511, 'bin': '835d5f38ec41cdfd862f84e3459532d4b8fecfe0496dd6c5402cc0aa4912127bbeb803360f620b001386e2d84fe2db9f6ad4574c654f955005521bcc8f56faa8'}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:38,477 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:38,479 DEBUG core.py Auth message = {'response': 511, 'bin': '835d5f38ec41cdfd862f84e3459532d4b8fecfe0496dd6c5402cc0aa4912127bbeb803360f620b001386e2d84fe2db9f6ad4574c654f955005521bcc8f56faa8'}
2024-01-08 18:56:38,479 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>, {'response': 200}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:38,985 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:38,985 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1704729398.479726, 'account_name': 'two'}
2024-01-08 18:56:38,986 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>, {'response': 202, 'data_list': ['one', 'two']}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:39,488 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:39,488 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1704729398.996454, 'user': 'two'}
2024-01-08 18:56:39,492 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:46,007 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:46,007 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1704729405.042222, 'user': 'two', 'account_name': 'one'}
2024-01-08 18:56:46,020 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>, {'response': 200}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:50,529 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:50,529 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1704729410.180771, 'account_name': 'one'}
2024-01-08 18:56:50,532 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyJamJnF6vbKpZY84HAgc\nlOgxj8bx2d8N9ITHwvJ2Cx5LDsaqGbanovcyP5Oo9VEIJgf53QWkYSTf2HxDBdPG\nxrhbzr7ho5yteGLTqsTpM/C0bVLsC8x5+MkT+Hv+H8Rw32o4RYiwCCvTOzkbODkn\nfCfebpFJcg16mo+TDctFOQ880qAZmAv8rfud36Za1Z7SefZyFcvD6bnxEN7yfpST\nr4IawraKkSqvm5XirEhmN/iEn/JBvHIWsCK9WpezsT9n+Dy1KNp9KNOXvgX77c9+\nFQ6j2ZHpA0TkWYG+N+wL9bbgGYlEtVrzZYRWcRoUPKuTstIXfFH7hkTYcbuuMyqu\nLwIDAQAB\n-----END PUBLIC KEY-----'}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:58,047 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:56:58,048 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'two', 'to': 'one', 'time': 1704729417.213134, 'mess_text': 'C4H/SSVdnUGeqSBIc/U0TXsRTdpmOTrLngvoDwV/iKP62h7lGO3iswzwdUzopdY9U3hGKdw6K3VCcbrJWyOp2LWC8M8oO67LRLRgF1xQNG3DptoyS0AMFFt2eWJBQB8jL8iW6c//s2LiT3p2mkpGl4ZjzumhhnX83+Dj/x5ioGGXWprFXPdRf/WraU4VOoy/uH+6Pf9xgsv9+8YEXTcd+3fi9i4+YpmHFKLM1JS2/Vta8yiktVuS3qUutWUeMxC87ns79TYDLhEIHQ/KoHRdcjDdRsOX0qyPkjTz21WgsB/r9PL5Xfio5wl6c+cpLOE/+74soBu+AsHVHHNfgdu69A=='}
2024-01-08 18:56:58,059 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'action': 'message', 'from': 'two', 'to': 'one', 'time': 1704729417.213134, 'mess_text': 'C4H/SSVdnUGeqSBIc/U0TXsRTdpmOTrLngvoDwV/iKP62h7lGO3iswzwdUzopdY9U3hGKdw6K3VCcbrJWyOp2LWC8M8oO67LRLRgF1xQNG3DptoyS0AMFFt2eWJBQB8jL8iW6c//s2LiT3p2mkpGl4ZjzumhhnX83+Dj/x5ioGGXWprFXPdRf/WraU4VOoy/uH+6Pf9xgsv9+8YEXTcd+3fi9i4+YpmHFKLM1JS2/Vta8yiktVuS3qUutWUeMxC87ns79TYDLhEIHQ/KoHRdcjDdRsOX0qyPkjTz21WgsB/r9PL5Xfio5wl6c+cpLOE/+74soBu+AsHVHHNfgdu69A=='}) , {}. Вызов из модуля core.utils
2024-01-08 18:56:58,059 INFO core.py Отправлено сообщение пользователю one от пользователя two.
2024-01-08 18:56:58,059 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>, {'response': 200}) , {}. Вызов из модуля core.utils
2024-01-08 18:57:10,085 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:57:10,086 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1704729429.585448, 'user': 'one', 'account_name': 'two'}
2024-01-08 18:57:10,095 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 200}) , {}. Вызов из модуля core.utils
2024-01-08 18:57:11,599 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:57:11,600 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1704729431.441679, 'account_name': 'two'}
2024-01-08 18:57:11,602 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArC0Y2Ag0NY64QTpSe14D\nVa17GtdYoN8zYGrsmHY3QhWHKdHwWpDzVYKW6ZpSLALwdGGL9FfogQ0Q/rBG/CUl\nFrT619HaTTkWn+jPw+uxrbh9PS1pRHlCydjNydtEo71Sr/LVv3xIznMuRobj7RPO\nPoT4d64UJ0n3BrPpzC7UUXcXFzL6V8FmCm5Waqj/3XQR+UBMs4PsMgjOiJllc3q7\nrsifd0KxtFOizYvvIP3U8/XuLriKLjhiJGXx8GAXiBS5jVHBDaRLrbJUtAeFV4nX\nDbVXXHWKIyTpjEEdia/bTcHamyWYqo36r0ES+U83LH4ENMPfh1XBW0ncmIm96XMd\n4wIDAQAB\n-----END PUBLIC KEY-----'}) , {}. Вызов из модуля core.utils
2024-01-08 18:57:20,623 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:57:20,623 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'one', 'to': 'two', 'time': 1704729440.49526, 'mess_text': 'QZ/IfWeMbu96a8qMw1OOIBJczHx0UtlkgJgwWM8MitRay7JhLvfQHOnXdrTQ4cZuJkKrrHmasTztcTsHAHBNTfbCFaq8CSsAbxVmCfn6TSZUR/jB18edAhQwOTFY/lXLBqpxlRBFMrRuWho+wpQX89jg70NaftZxXc6StQqQASjmeyRXXqkJwouBy0Dh8uAJlj98O7Oagxwhw+bONyHX6hAcLRr5XuYRHmewUQKts2J7mXkPn9cFfMLP27Tf1aEyyuhEzjOOcpo/t3kJqtiW0piCLS5SCVjbvZbgZGCDsgeZCAhasdC3CEqVvnrVo0EPSxzLdSy8OtEGN4ce9bzuzQ=='}
2024-01-08 18:57:20,631 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>, {'action': 'message', 'from': 'one', 'to': 'two', 'time': 1704729440.49526, 'mess_text': 'QZ/IfWeMbu96a8qMw1OOIBJczHx0UtlkgJgwWM8MitRay7JhLvfQHOnXdrTQ4cZuJkKrrHmasTztcTsHAHBNTfbCFaq8CSsAbxVmCfn6TSZUR/jB18edAhQwOTFY/lXLBqpxlRBFMrRuWho+wpQX89jg70NaftZxXc6StQqQASjmeyRXXqkJwouBy0Dh8uAJlj98O7Oagxwhw+bONyHX6hAcLRr5XuYRHmewUQKts2J7mXkPn9cFfMLP27Tf1aEyyuhEzjOOcpo/t3kJqtiW0piCLS5SCVjbvZbgZGCDsgeZCAhasdC3CEqVvnrVo0EPSxzLdSy8OtEGN4ce9bzuzQ=='}) , {}. Вызов из модуля core.utils
2024-01-08 18:57:20,631 INFO core.py Отправлено сообщение пользователю two от пользователя one.
2024-01-08 18:57:20,631 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>, {'response': 200}) , {}. Вызов из модуля core.utils
2024-01-08 18:57:41,674 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=18, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50743)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:57:41,675 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1704729461.638032, 'account_name': 'two'}
2024-01-08 18:57:41,675 INFO core.py Клиент ('127.0.0.1', 50743) отключился от сервера.
2024-01-08 18:57:44,684 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50733)>,) , {}. Вызов из модуля core.utils
2024-01-08 18:57:44,684 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1704729464.531578, 'account_name': 'one'}
2024-01-08 18:57:44,685 INFO core.py Клиент ('127.0.0.1', 50733) отключился от сервера.
2024-01-08 18:59:25,984 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 18:59:25,984 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 18:59:25,984 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 18:59:25,985 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/./server/server.py']
2024-01-08 18:59:25,985 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:00:30,978 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:00:30,978 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:00:30,978 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:00:30,979 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/./server/server.py']
2024-01-08 19:00:30,979 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:03:44,676 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:03:44,676 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:03:44,677 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:03:44,677 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/./server/server.py']
2024-01-08 19:03:44,677 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:04:40,363 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:04:40,363 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:04:40,363 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:04:40,363 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/./server/server.py']
2024-01-08 19:04:40,364 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:08:41,004 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:08:41,005 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:08:41,005 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:08:41,005 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/./server/server.py']
2024-01-08 19:08:41,006 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:09:45,061 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:09:45,061 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:09:45,061 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:09:45,062 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['/Users/macbook/Code/Demo/_progress/chat_gui_example_GitHub_pyqt/./server/server.py']
2024-01-08 19:09:45,062 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:10:06,930 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:10:06,930 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:10:06,930 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:10:06,930 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['./server/server.py']
2024-01-08 19:10:06,931 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:10:33,313 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:10:33,313 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:10:33,313 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:10:33,313 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['./server.py']
2024-01-08 19:10:33,314 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:10:33,320 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2024-01-08 19:12:08,885 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:12:08,886 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:12:08,886 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:12:08,886 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['./server.py']
2024-01-08 19:12:08,887 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:12:08,892 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2024-01-08 19:12:16,979 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:12:16,979 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:12:16,980 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:12:16,980 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['./server/server.py']
2024-01-08 19:12:16,981 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:12:16,985 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2024-01-08 19:13:00,611 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:13:00,611 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:13:00,612 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:13:00,612 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['./server/server.py']
2024-01-08 19:13:00,613 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:13:12,262 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:13:12,262 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:13:12,262 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:13:12,262 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['./server/server.py']
2024-01-08 19:13:12,263 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:13:30,178 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:13:30,178 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:13:30,179 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:13:30,179 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['./server/server.py']
2024-01-08 19:13:30,180 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:14:42,198 DEBUG logger.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:14:42,198 DEBUG logger.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2024-01-08 19:14:42,199 DEBUG logger.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2024-01-08 19:14:42,199 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['./server/server.py']
2024-01-08 19:14:42,199 DEBUG server.py Аргументы успешно загружены.
2024-01-08 19:14:42,204 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2024-01-08 19:16:06,219 INFO core.py Установлено соедение с ПК ('127.0.0.1', 51087)
2024-01-08 19:16:06,721 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51087)>,) , {}. Вызов из модуля core.utils
2024-01-08 19:16:06,722 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1704730566.228271, 'user': {'account_name': 'one', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyJamJnF6vbKpZY84HAgc\nlOgxj8bx2d8N9ITHwvJ2Cx5LDsaqGbanovcyP5Oo9VEIJgf53QWkYSTf2HxDBdPG\nxrhbzr7ho5yteGLTqsTpM/C0bVLsC8x5+MkT+Hv+H8Rw32o4RYiwCCvTOzkbODkn\nfCfebpFJcg16mo+TDctFOQ880qAZmAv8rfud36Za1Z7SefZyFcvD6bnxEN7yfpST\nr4IawraKkSqvm5XirEhmN/iEn/JBvHIWsCK9WpezsT9n+Dy1KNp9KNOXvgX77c9+\nFQ6j2ZHpA0TkWYG+N+wL9bbgGYlEtVrzZYRWcRoUPKuTstIXfFH7hkTYcbuuMyqu\nLwIDAQAB\n-----END PUBLIC KEY-----'}}
2024-01-08 19:16:06,722 DEBUG core.py Start auth process for {'account_name': 'one', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyJamJnF6vbKpZY84HAgc\nlOgxj8bx2d8N9ITHwvJ2Cx5LDsaqGbanovcyP5Oo9VEIJgf53QWkYSTf2HxDBdPG\nxrhbzr7ho5yteGLTqsTpM/C0bVLsC8x5+MkT+Hv+H8Rw32o4RYiwCCvTOzkbODkn\nfCfebpFJcg16mo+TDctFOQ880qAZmAv8rfud36Za1Z7SefZyFcvD6bnxEN7yfpST\nr4IawraKkSqvm5XirEhmN/iEn/JBvHIWsCK9WpezsT9n+Dy1KNp9KNOXvgX77c9+\nFQ6j2ZHpA0TkWYG+N+wL9bbgGYlEtVrzZYRWcRoUPKuTstIXfFH7hkTYcbuuMyqu\nLwIDAQAB\n-----END PUBLIC KEY-----'}
2024-01-08 19:16:06,727 DEBUG core.py Correct username, starting passwd check.
2024-01-08 19:16:06,727 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51087)>, {'response': 511, 'bin': 'f638ba4a91d937aecd0cf548421c30f44fd2c66c3267d9bba63a628b2bc531e46f9b5c7a5b91aba3fe5fb372c7fb880649898298fa4d5c4586889e7325140af1'}) , {}. Вызов из модуля core.utils
2024-01-08 19:16:06,728 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51087)>,) , {}. Вызов из модуля core.utils
2024-01-08 19:16:06,730 DEBUG core.py Auth message = {'response': 511, 'bin': 'f638ba4a91d937aecd0cf548421c30f44fd2c66c3267d9bba63a628b2bc531e46f9b5c7a5b91aba3fe5fb372c7fb880649898298fa4d5c4586889e7325140af1'}
2024-01-08 19:16:06,730 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51087)>, {'response': 200}) , {}. Вызов из модуля core.utils
2024-01-08 19:16:07,250 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51087)>,) , {}. Вызов из модуля core.utils
2024-01-08 19:16:07,251 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1704730566.7314188, 'account_name': 'one'}
2024-01-08 19:16:07,253 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51087)>, {'response': 202, 'data_list': ['one']}) , {}. Вызов из модуля core.utils
2024-01-08 19:16:07,754 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51087)>,) , {}. Вызов из модуля core.utils
2024-01-08 19:16:07,754 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1704730567.260423, 'user': 'one'}
2024-01-08 19:16:07,761 DEBUG logger.py Была вызвана функция send_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51087)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля core.utils
2024-01-08 19:16:49,361 DEBUG logger.py Была вызвана функция get_message c параметрами (<socket.socket fd=13, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51087)>,) , {}. Вызов из модуля core.utils
2024-01-08 19:16:49,362 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1704730609.308068, 'account_name': 'one'}
2024-01-08 19:16:49,362 INFO core.py Клиент ('127.0.0.1', 51087) отключился от сервера.
